# -*- coding: utf-8 -*-
"""Hand-drawn main-character portraits for the banner heroes.

Cells:  ' ' empty, '#' outline, 'S' skin, 'H' hair, 'E' eye,
        'M' mouth, 'W' white/highlight.
Each character is a list of fixed-width rows; colors are applied
per-skin by the generator.
"""

CHARACTERS = {
    "ben": [
        "      HH   HH   HH       ",
        "    HHHHHHHHHHHHHHHHHH   ",
        "   HHHHHHHHHHHHHHHHHHHH  ",
        "   HHHHHHHHHHHHHHHHHHHH  ",
        "   ##SSSSSSSSSSSSSSSS##  ",
        "  #SSSSSSSSSSSSSSSSSSSS# ",
        "  #SSSSSSSSSSSSSSSSSSSS# ",
        "  #SSSSEE SSSSSS EESSSS# ",
        "  #SSSSEE SSSSSS EESSSS# ",
        "  #SSSSSSSSSSSSSSSSSSSS# ",
        "   ##SSSSSSSSSSSSSSSS##  ",
        "   ##SSSSMSSSSSSMSSSS##  ",
        "   #SSSSSSSSSSSSSSSSSS#  ",
        "   #SSSSSSSSSSSSSSSSSS#  ",
        "    ##################   ",
    ],
    "ppg": [
        "   ##      ##      ##   ",
        "  ####    ####    ####  ",
        "  #SS##   #SS##   #SS## ",
        "  #SSSS#  #SSSS#  #SSSS#",
        "  #SSSSS# #SSSSS# #SSSSS#",
        "  #SSSSS# #SSSSS# #SSSSS#",
        "  #SEESS# #SEESS# #SEESS#",
        "  #SSSSS# #SSSSS# #SSSSS#",
        "  ##SSS## ##SSS## ##SSS##",
    ],
    "dexter": [
        "     HHHHHHHHHH     ",
        "    HHHHHHHHHHHHHH  ",
        "   HH##########HH   ",
        "  #HSSSSSSSSSSSSH#  ",
        "  #SSSSSSSSSSSSSS#  ",
        "  #SS##SSSSSS##SS#  ",
        "  #SS##SSSSSS##SS#  ",
        "  #SSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSS##  ",
        "   ##############   ",
    ],
    "bravo": [
        "    HH      HH HH    ",
        "   HHHHHHHHHHHHHH    ",
        "  HHHHHHHHHHHHHHHH   ",
        "  ##HHSSSSSSSSHH##   ",
        "  ##SSSSSSSSSSSS##   ",
        "  #SSSSEESSEESSSSS#  ",
        "  #SSSSEESSEESSSSS#  ",
        "  #SSSSSSSSSSSSSS#   ",
        "  ##SSSMMSSSSMMSS##  ",
        "   ##############    ",
    ],
    "courage": [
        "  ##  ##      ##  ## ",
        " #########  #########",
        " ##SS############SS##",
        " ##SSSSSSSSSSSSSSSS##",
        " #SSSSSSSSSSSSSSSSSS#",
        " #SSSSSSSSSSSSSSSSSS#",
        " #SSEE SS SS SS EESS#",
        " #SSSSSSSSSSSSSSSSSS#",
        " ##SSSMS SS SS SMMS##",
        "  ##SSSSSSSSSSSSSS## ",
        "   ################  ",
    ],
    "knd": [
        "    HHHHHHHHHHHHH    ",
        "   HHHHHHHHHHHHHHH   ",
        "   HHSSSSSSSSSSSHH   ",
        "  ##SSSSSSSSSSSSSS## ",
        "  #SSSSSSSSSSSSSSSS# ",
        "  #SSSSSSSSSSSSSSSS# ",
        "  #SSEE SS SS EESSS# ",
        "  #SSSSSSSSSSSSSSSS# ",
        "  ##SSSSSSSSSSSSSS## ",
        "   ################  ",
    ],
    "bloo": [
        "      ##########      ",
        "    ##############    ",
        "   ################   ",
        "  ##################  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSEE SSSSSS EESS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "   ######SSSS######   ",
    ],
    "jack": [
        "   HHHHHHHHHHHHHHHH   ",
        "  HHHHHHHHHHHHHHHHHH  ",
        "  HH############HH    ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  ##SSEE SS SS EESS## ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  ##SSSMMSSSSSSMMS##  ",
        "   ################   ",
    ],
    "finn": [
        "   HHHH   HHHH   HHHH   ",
        "  HHHHHHHHHHHHHHHHHHHH  ",
        "  HHHHHHHHHHHHHHHHHHHH  ",
        "  HH############HH      ",
        "  ##SSSSSSSSSSSS##      ",
        "  ##SSSSSSSSSSSS##      ",
        "  #SSSSSSSSSSSSSS#      ",
        "  #SSSSSSSSSSSSSS#      ",
        "  #SSEE SSSS EESS#      ",
        "  #SSSSSSSSSSSSSS#      ",
        "  ##SSSSSSSSSSSS##      ",
        "   ##############       ",
    ],
    "mordecai": [
        "     HHHHHH  HH       ",
        "    HHHHHHHHHHHH      ",
        "   HHHHHHHHHHHHHHHH   ",
        "   ##SSSSSSSSSSSS##   ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSEE SS SS EESSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  ##SSSMMSSSSSSMMS##  ",
        "   ################   ",
    ],
    "gumball": [
        "     ##########     ",
        "    ############    ",
        "   ##############   ",
        "   ##SSSSSSSSSS##   ",
        "  #SSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSS#  ",
        "  #SSEE SSSS EESS#  ",
        "  #SSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSS##  ",
        "   ##############   ",
    ],
    "steven": [
        "   ##  ##  ##  ##   ",
        "   ##############   ",
        "  ##############    ",
        "  ##SSSSSSSSSS##    ",
        "  #SSSSSSSSSSSS#    ",
        "  #SSSSSSSSSSSS#    ",
        "  #SSEE SSSS EE#    ",
        "  #SSSSSSSSSSSS#    ",
        "  ##SSSSSSSSSS##    ",
        "  ##############    ",
    ],
    "bears": [
        "   ##      ##      ##   ",
        "  ####    ####    ####  ",
        "  #SS##   #SS##   #SS## ",
        "  #SSSS#  #SSSS#  #SSSS#",
        "  #SEES#  #SEES#  #SEES#",
        "  #SSSS#  #SSSS#  #SSSS#",
        "  ##SS##  ##SS##  ##SS##",
    ],
    "batman": [
        "       #########       ",
        "      ###########      ",
        "      ##SSSSSSS##      ",
        "     #SSSSSSSSSSS#     ",
        "    #SSSSSSSSSSSSS#    ",
        "   #SSSSSSSSSSSSSSS#   ",
        "  ##SSSSSSSSSSSSSSS##  ",
        "  #SSSSSSSSSSSSSSSSS#  ",
        "  #SSWWWSSSSSSSWWWSS#  ",
        "  #SSWWWSSSSSSSWWWSS#  ",
        "  #SSSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSSS##  ",
        "   ##################  ",
    ],
    "beyond": [
        "       #########       ",
        "      ###########      ",
        "      ##SSSSSSS##      ",
        "     ##WWWWWWWWW##     ",
        "     #WWEEWWWWEEWW#    ",
        "     #WWWWWWWWWWWW#    ",
        "    #SSSSSSSSSSSSSS#   ",
        "   #SSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSSSS## ",
        "  #SSSSSSSSSSSSSSSSSS# ",
        "  ##SSSSSSSSSSSSSSSS## ",
        "   ##################  ",
    ],
    "clone": [
        "    ################    ",
        "   ##################   ",
        "  ##SSSSSSSSSSSSSSSS##  ",
        "  ##SSSSSSSSSSSSSSSS##  ",
        "  ##SSWWSSSSSSSSWWSS##  ",
        "  ##SSWWSSSSSSSSWWSS##  ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "   ##SSSSSSSSSSSSSS##   ",
        "    ################    ",
    ],
    "ninja": [
        "    HHHHHHHHHHHHHH    ",
        "   HHHHHHHHHHHHHHHH   ",
        "   ##SSSSSSSSSSSS##   ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSEE SSSS SS EES#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "  ##################  ",
    ],
    "goku": [
        "    HH  HH  HH  HH    ",
        "  HH HHHHHHHHHHHH HH  ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " ##SSSSSSSSSSSSSSSS## ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSEE SSSS EESSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " ##SSSSSSSSSSSSSSSS## ",
        "  ##################  ",
    ],
    "naruto": [
        "    HH  HH  HH  HH    ",
        "  HHHHHHHHHHHHHHHHHH  ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " ##SSSSSSSSSSSSSSSS## ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSEE SSSS EESSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SS###############S# ",
        " ##SSSSSSSSSSSSSSSS## ",
        "  ##################  ",
    ],
    "luffy": [
        "   ###################  ",
        "  ######################",
        "  ######################",
        "  ##SSSSSSSSSSSSSSSSSS##",
        "  ##SSSSSSSSSSSSSSSSSS##",
        "  #SSSSSSSSSSSSSSSSSSSS#",
        "  #SSSSSSSSSSSSSSSSSSSS#",
        "  #SSSSEE SSSSSS EESSSS#",
        "  #SSSSSSSSSSSSSSSSSSSS#",
        "  #SSSSSSSSSSSSSSSSSSSS#",
        "  ##SSSSSSSSSSSSSSSSSS##",
        "  ######################",
    ],
    "deku": [
        "      HH   HH   HH      ",
        "    HHHHHHHHHHHHHHHH    ",
        "   HHHHHHHHHHHHHHHHHH   ",
        "   ##SSSSSSSSSSSSSS##   ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "  #SSSSEE SSSS EESSSS#  ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSSSS##  ",
        "   ##################   ",
    ],
    "saitama": [
        "      ##########      ",
        "     ############     ",
        "    ##############    ",
        "   ################   ",
        "   ##SSSSSSSSSSSS##   ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSEE SSSS EESS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSSSSSS##  ",
        "   ################   ",
    ],
    "gundam": [
        "        HH  HH        ",
        "       HHHHHHHH       ",
        "      HHHHHHHHHHHH    ",
        "     #SSSSSSSSSSSS#   ",
        "    #SSSSSSSSSSSSSS#  ",
        "    #SSSSSSSSSSSSSS#  ",
        "    #SSWWSSSSSSWWSS#  ",
        "    #SSWWSSSSSSWWSS#  ",
        "    #SSSSSSSSSSSSSS#  ",
        "     ##SSSSSSSSSS##   ",
        "      ############    ",
    ],
    "usagi": [
        "    HH      HH    ",
        "   HHHH    HHHH   ",
        "  ##SS####SS##    ",
        "  ##SSSSSSSS##    ",
        "  #SSSSSSSSSS#    ",
        "  #SSSSSSSSSS#    ",
        "  #SSEE SS EE#    ",
        "  #SSSSSSSSSS#    ",
        "  ##SSSSSSSS##    ",
        "  ############    ",
    ],
    "rick": [
        "  HH    HH  HH    HH  ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " HHHHHHHHHHHHHHHHHHHH ",
        " ##SSSSSSSSSSSSSSSS## ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SS##SSSSSSSS##SSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " #SSSSSSSSSSSSSSSSSS# ",
        " ##SSSSSSSSSSSSSSSS## ",
        "  ##################  ",
    ],
    "shake": [
        "         ###         ",
        "        #####        ",
        "       #######       ",
        "       #SS###        ",
        "       #SSSSS#       ",
        "      #SSSSSSS#      ",
        "      #SSSSSSS#      ",
        "      #SSSSSSS#      ",
        "       #SSSSS#       ",
        "       #SSSSS#       ",
        "        #####        ",
    ],
    "tomcat": [
        "  ##        ##  ",
        " ####      #### ",
        " ##SS##    ##SS##",
        " ##SSSS## ##SSSS#",
        " #SSSSSS# #SSSSSS",
        " #SSSSSSS#SSSSSSS",
        " #SSSSSSSSSSSSSSS",
        " #SSEE SSSS EESS#",
        " #SSSSSSSSSSSSSS#",
        " ##SSSSSSSSSSSS##",
        "  ############## ",
    ],
    "scooby": [
        "  ####      ####  ",
        "  ##SS##    ##SS##",
        "  ##SSSS##  ##SSSS",
        "  #SSSSSSSSSSSSSS#",
        "  #SSSSSSSSSSSSSS#",
        "  #SSEE SS SS EES#",
        "  #SSSSSSSSSSSSSS#",
        "  ##SSSMS SS SMMS#",
        "   ############## ",
    ],
    "garfield": [
        "   ############   ",
        "  ##############  ",
        "  ##############  ",
        "  ##SSSSSSSSSS##  ",
        "  #SSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSS#  ",
        "  #SSMM SS SS MM# ",
        "  #SSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSS##  ",
        "   ############   ",
    ],
    "optimus": [
        "    ####  ####    ",
        "   ##SS####SS##   ",
        "  ##SSSSSSSSSSSS##",
        "  #SSSSSSSSSSSSSS#",
        "  #SSWWSSSSSSWWSS#",
        "  #SSWWSSSSSSWWSS#",
        "  #SSSSSSSSSSSSSS#",
        "  ##SSSSSSSSSSSS##",
        "   ############## ",
    ],
    "megaman": [
        "    ##########    ",
        "   ############   ",
        "  ##############  ",
        "  ##SSSSSSSSSS##  ",
        "  #SSSSSSSSSSSS#  ",
        "  #SSSSSSSSSSSS#  ",
        "  #SSWWSSSSWWSS#  ",
        "  #SSWWSSSSWWSS#  ",
        "  #SSSSSSSSSSSS#  ",
        "  ##SSSSSSSSSS##  ",
        "  ##############  ",
    ],
    "tom": [
        "   ##############  ",
        "  ##SSSSSSSSSSSS## ",
        "  #SSSSSSSSSSSSSS# ",
        "  #SSWWSSSSSSWWSS# ",
        "  #SSWWSSSSSSWWSS# ",
        "  #SSSSSSSSSSSSSS# ",
        "  ##SSSSSSSSSSSS## ",
        "  ################ ",
    ],
}
