# -*- coding: utf-8 -*-
"""Cartoon Network skin database, part 1.

Field order per entry:
slug, title, desc, agent, welcome, goodbye, sym, verbs, p, s, a, bg, tx, cat, logo
- p/s/a/bg/tx = primary, secondary, accent, background, text hex colors
- logo: optional override for the ASCII banner text (defaults to title)
"""

SHOWS_A = [
    # ---------------- Ben 10 Universe ----------------
    ("ben-10", "Ben 10", "Classic Omnitrix series — dial in a hero and save the world.",
     "Omnitrix Agent", "It's hero time! Type your message or /help to save the day.",
     "Guess that's all the aliens I need. Later, hero!",
     "⌁", ["dialing alien DNA", "scanning new species", "unlocking the Omnitrix", "transforming", "saving the day"],
     "#16C784", "#A7F3D0", "#F5F5F5", "#0A0E0A", "#EAF7EE", "Ben 10 Universe", "BEN 10"),

    ("ben-10-alien-force", "Ben 10: Alien Force", "Teen Ben leads a team against the Highbreed invasion.",
     "Alien Force Agent", "Alien Force online. Type your message or /help to join the team.",
     "Deactivating the Omnitrix. See you, hero.",
     "◈", ["assembling the team", "tracking the Highbreed", "summoning aliens", "mapping the galaxy", "leading the charge"],
     "#3B82F6", "#93C5FD", "#FFFFFF", "#05070D", "#DCE6F5", "Ben 10 Universe", "ALIEN FORCE"),

    ("ben-10-ultimate-alien", "Ben 10: Ultimate Alien", "The Ultimatrix era — every transformation, one step further.",
     "Ultimatrix Agent", "Ultimatrix ready. Type your message or /help and evolve.",
     "Ultimatrix powering down. Stay ultimate!",
     "▲", ["evolving the Ultimatrix", "unleashing ultimate forms", "scanning the map of infinity", "analyzing the threat", "going ultimate"],
     "#DC2626", "#F87171", "#FFFFFF", "#0D0505", "#F5E0E0", "Ben 10 Universe", "ULTIMATE ALIEN"),

    ("ben-10-omniverse", "Ben 10: Omniverse", "New Omnitrix, new universe, same hero time.",
     "Omniverse Agent", "Omnitrix rebooted. Type your message or /help for alien action.",
     "Closing the rift. See you in another universe!",
     "❖", ["rebooting the Omnitrix", "mixing alien powers", "fixing the timeline", "exploring Omniverse", "dodging Khyber"],
     "#22D3EE", "#FFFFFF", "#F97316", "#060B0F", "#E6F4F8", "Ben 10 Universe", "OMNIVERSE"),

    ("ben-10-2016", "Ben 10 (2016)", "The reboot — Ben, Gwen and Max on the road with the Omnitrix.",
     "Omnitrix Agent", "Road trip hero time! Type your message or /help to go alien.",
     "Omnitrix in sleep mode. Later, hero!",
     "✺", ["going hero time", "testing the Omnitrix", "sneaking past Gwen", "making alien choices", "saving the summer"],
     "#22C55E", "#A3E635", "#38BDF8", "#0A100A", "#EAF7EC", "Ben 10 Universe", "BEN 10"),

    ("generator-rex", "Generator Rex", "Nanite-built machines and EVO battles from the Ben 10 universe.",
     "Providence Agent", "Nanites ready. Type your message or /help to build something.",
     "Machines powered down. Stay smashing!",
     "⌬", ["building machines", "deploying nanites", "scanning EVOs", "powering up the Smack Hands", "chasing Van Kleiss"],
     "#34D399", "#A7F3D0", "#22D3EE", "#04120B", "#DDF5EA", "Ben 10 Universe", "GEN REX"),

    # ---------------- Cartoon Cartoons & Classics ----------------
    ("powerpuff-girls", "The Powerpuff Girls", "Sugar, spice and everything nice — Townsville's tiny protectors.",
     "Powerpuff Agent", "Crime fighting before bedtime! Type your message or /help.",
     "Bedtime! The city is safe... for now. ♥",
     "♥", ["fighting crime", "saving Townsville", "sugar-spicing", "blossoming plans", "bedtime-ing"],
     "#F472B6", "#60A5FA", "#4ADE80", "#170B14", "#FBEAF3", "Cartoon Cartoons & Classics", "POWERPUFF"),

    ("powerpuff-girls-2016", "The Powerpuff Girls (2016)", "The reboot — same trio, brighter neon and new baddies.",
     "Powerpuff Agent", "Who's gonna save the world today? Type your message or /help!",
     "Superheroes need rest too. Night!",
     "★", ["super-speeding", "punching baddies", "saving the day", "fighting Mojo Jojo", "zooming home"],
     "#F472B6", "#38BDF8", "#A3E635", "#120A18", "#FBEAF3", "Cartoon Cartoons & Classics", "POWERPUFF 2016"),

    ("dexter-laboratory", "Dexter's Laboratory", "The boy genius and his secret lab full of inventions.",
     "Dexter Agent", "Ooo, what does this button do? Type your message or /help!",
     "Experiment complete. Goodbye!",
     "⚗", ["running experiments", "engineering a device", "keeping it secret", "avoiding Dee Dee", "labeling everything"],
     "#14B8A6", "#F472B6", "#FDE047", "#071412", "#DDF3F0", "Cartoon Cartoons & Classics", "DEXTER'S LAB"),

    ("johnny-bravo", "Johnny Bravo", "The muscle-bound, hair-combing ladies' man of Aron City.",
     "Johnny Bravo Agent", "Hey there, good lookin'! Type your message or /help... uh-huh.",
     "Gotta go comb my hair. Later, baby!",
     "♪", ["flexing", "combing hair", "smooth-talking", "striking a pose", "dancing with mom"],
     "#38BDF8", "#FDE047", "#FB7185", "#0A1018", "#E8F1F8", "Cartoon Cartoons & Classics", "JOHNNY BRAVO"),

    ("courage-the-cowardly-dog", "Courage the Cowardly Dog", "A scaredy-cat dog protecting his owners in Nowhere.",
     "Courage Agent", "The things I do for love... Type your message or /help. Stupid dog!",
     "Finally, quiet in Nowhere. Goodbye!",
     "☎", ["staying very still", "answering the phone", "surviving Nowhere", "facing the strange", "protecting Muriel"],
     "#A855F7", "#F472B6", "#FDE047", "#0D0814", "#F0E8F8", "Cartoon Cartoons & Classics", "COURAGE"),

    ("ed-edd-n-eddy", "Ed, Edd n Eddy", "Three friends, endless scams and one huge jawbreaker.",
     "Eddy Agent", "Scam alert! Type your message or /help for jawbreakers.",
     "Out of jawbreakers. See ya, chowderheads!",
     "◉", ["collecting jawbreakers", "scamming for quarters", "planning a scam", "double-dealing", "hiding from the Kankers"],
     "#FB923C", "#FDE047", "#FDBA74", "#120B05", "#F8EFE0", "Cartoon Cartoons & Classics", "ED EDD N EDDY"),

    ("kids-next-door", "Codename: Kids Next Door", "Five kids, a treehouse and a mission to fight adult tyranny.",
     "KND Operative", "KND sector online. Type your message or /help, operative.",
     "Mission accomplished. Treehouse out!",
     "▣", ["deploying operatives", "raiding the treehouse", "striking the Delightful Children", "securing the sector", "fighting adult tyranny"],
     "#22C55E", "#E5E7EB", "#FACC15", "#07140A", "#E7F4EA", "Cartoon Cartoons & Classics", "KND"),

    ("fosters-home", "Foster's Home for Imaginary Friends", "A mansion full of imaginary friends waiting for adoption.",
     "Blooregard Agent", "Welcome to Foster's! Type your message or /help, new friend.",
     "Time for a nap. Goodbye, friend!",
     "✿", ["imagining friends", "adopting out", "shuffling the house", "avoiding Madame Foster", "helping Bloo"],
     "#7DD3FC", "#F9A8D4", "#FDE68A", "#0B1420", "#EAF4FB", "Cartoon Cartoons & Classics", "FOSTERS"),

    ("grim-adventures-of-billy-mandy", "The Grim Adventures of Billy & Mandy", "Grim, Billy and Mandy — the weirdest trio this side of Endsville.",
     "Grim Agent", "Heh heh heh. Type your message or /help if you dare.",
     "I'm outta here. See ya, Billy!",
     "☠", ["scything", "cursing deals", "enduring Billy", "suffering Mandy", "visiting Endsville"],
     "#4ADE80", "#A3E635", "#F87171", "#08110A", "#E9F6ED", "Cartoon Cartoons & Classics", "BILLY & MANDY"),

    ("samurai-jack", "Samurai Jack", "A samurai trapped in a future ruled by the demon Aku.",
     "Samurai Jack Agent", "I must get back to the past! Type your message or /help.",
     "Farewell. The battle continues.",
     "⚔", ["severing evil", "training with the katana", "hunting Aku", "surviving the future", "mastering the blade"],
     "#EF4444", "#F8FAFC", "#2DD4BF", "#0D0507", "#F6E9E9", "Cartoon Cartoons & Classics", "SAMURAI JACK"),

    ("cow-and-chicken", "Cow and Chicken", "The adventures of a cow and her chicken brother.",
     "Cow & Chicken Agent", "Moo! Type your message or /help, cousin.",
     "Moo moo! Goodbye!",
     "●", ["mooing", "outsmarting the Red Guy", "bothering Dad", "hiding the plan", "being a cow"],
     "#EF4444", "#FDE047", "#F97316", "#140808", "#F8E9E9", "Cartoon Cartoons & Classics", "COW & CHICKEN"),

    ("i-am-weasel", "I Am Weasel", "I.M. Weasel, the brilliant one — and I.R. Baboon, his rival.",
     "I.M. Weasel Agent", "Ah, good day! Type your message or /help, if you can keep up.",
     "Until next time, you delightful creatures!",
     "☝", ["weaseling through", "showing off", "outsmarting Baboon", "being brilliant", "posing for portraits"],
     "#FACC15", "#2DD4BF", "#F87171", "#0E1208", "#F8F4E4", "Cartoon Cartoons & Classics", "I AM WEASEL"),

    ("2-stupid-dogs", "2 Stupid Dogs", "Little Dog and Big Dog — the two dumbest, happiest dogs around.",
     "Stupid Dog Agent", "Woof! Type your message or /help... if you can find it.",
     "Woof woof! See ya!",
     "◯", ["digging holes", "barking at nothing", "chasing tails", "getting lost", "being happy"],
     "#60A5FA", "#F8FAFC", "#FBBF24", "#0A1120", "#E7EEF8", "Cartoon Cartoons & Classics", "2 STUPID DOGS"),

    ("robot-jones", "Whatever Happened to Robot Jones?", "A robot kid navigating middle school in a retro-future.",
     "Robot Jones Agent", "Greetings. Type your message or /help, human.",
     "Shutting down for the night. Goodbye.",
     "▦", ["computing", "rebooting", "fitting in", "processing emotions", "attending middle school"],
     "#9CA3AF", "#F87171", "#FDE047", "#0E0F11", "#E9EAED", "Cartoon Cartoons & Classics", "ROBOT JONES"),

    ("mike-lu-og", "Mike, Lu & Og", "A city girl, a genius and a native boy on a tropical island.",
     "Island Agent", "Aloha! Type your message or /help and explore the island.",
     "See you on the beach!",
     "☼", ["island-hopping", "inventing gadgets", "learning island ways", "sunbathing", "discovering things"],
     "#2DD4BF", "#FB923C", "#FDE047", "#071A18", "#E2F5F2", "Cartoon Cartoons & Classics", "MIKE LU & OG"),

    ("sheep-in-the-big-city", "Sheep in the Big City", "An escaped military sheep living in the big city.",
     "Sheep Agent", "Baa! Type your message or /help. (That's sheep for hello.)",
     "Baa baa! Goodbye!",
     "☁", ["herding", "dodging the military", "losing the leash", "being woolly", "hiding from General Specific"],
     "#E5E7EB", "#9CA3AF", "#F87171", "#101216", "#EDEFF2", "Cartoon Cartoons & Classics", "SHEEP"),

    ("the-cramp-twins", "The Cramp Twins", "Identical twin brothers with opposite personalities.",
     "Cramp Agent", "Twins online! Type your message or /help, brother.",
     "Twin power out! Bye!",
     "☺", ["cramping up", "scheming", "being twins", "annoying the neighbors", "pulling pranks"],
     "#A3E635", "#FDE047", "#4ADE80", "#0F1408", "#F0F6E6", "Cartoon Cartoons & Classics", "CRAMP TWINS"),

    ("camp-lazlo", "Camp Lazlo", "Lazlo the bean scout monkey and the campers of Camp Kidney.",
     "Bean Scout Agent", "Camp Kidney welcomes you! Type your message or /help, scout.",
     "Camp's over. See you next summer!",
     "△", ["setting up camp", "saving the jellybeans", "bean-scouting", "raiding the mess hall", "hiding from Lumpus"],
     "#84CC16", "#F87171", "#FDE047", "#0C1406", "#F2F7E9", "Cartoon Cartoons & Classics", "CAMP LAZLO"),

    ("my-gym-partner-is-a-monkey", "My Gym Partner's a Monkey", "A boy transferred to a school for animals.",
     "Gym Partner Agent", "Monkey business time! Type your message or /help.",
     "Class dismissed! Later!",
     "∿", ["swinging by", "attending gym class", "hanging with the animals", "monkeying around", "skipping class"],
     "#D97706", "#84CC16", "#FBBF24", "#120C05", "#F5EEE4", "Cartoon Cartoons & Classics", "GYM MONKEY"),

    ("squirrel-boy", "Squirrel Boy", "A boy and his loud, squirrel best friend.",
     "Squirrel Agent", "Nuts! Type your message or /help, pal.",
     "Storing nuts for later. Bye!",
     "✺", ["hoarding nuts", "squirreling around", "planning mischief", "chasing acorns", "bugging Andy"],
     "#F97316", "#FDBA74", "#A3E635", "#140A04", "#F7EDE3", "Cartoon Cartoons & Classics", "SQUIRREL BOY"),

    ("hi-hi-puffy-amiyumi", "Hi Hi Puffy AmiYumi", "The real-life rock duo as cartoon adventures.",
     "Puffy Agent", "Let's rock! Type your message or /help and turn it up.",
     "Show's over! Rock on!",
     "♫", ["rocking out", "touring Japan", "jamming", "recording tracks", "meeting fans"],
     "#F472B6", "#38BDF8", "#FDE047", "#160A12", "#FBE9F2", "Cartoon Cartoons & Classics", "PUFFY AMIYUMI"),

    ("juniper-lee", "The Life and Times of Juniper Lee", "An 11-year-old secretly protecting the world from monsters.",
     "Juniper Agent", "Monster patrol active! Type your message or /help.",
     "No monsters today. Bye!",
     "✶", ["fighting monsters", "hiding magic", "keeping it secret", "saving the city", "dealing with the beasties"],
     "#A855F7", "#F87171", "#FDE047", "#0F0818", "#F2EAF8", "Cartoon Cartoons & Classics", "JUNIPER LEE"),

    ("class-of-3000", "Class of 3000", "Andre 3000 teaches music at a school in Atlanta.",
     "Class 3000 Agent", "Welcome to class! Type your message or /help, students.",
     "Class dismissed! Keep making music!",
     "♩", ["jamming", "teaching music", "singing", "composing", "making beats"],
     "#EF4444", "#FDE047", "#38BDF8", "#150808", "#F9E9E9", "Cartoon Cartoons & Classics", "CLASS OF 3000"),

    ("mucha-lucha", "Mucha Lucha!", "Masked luchadores wrestling for honor at the International School of Lucha.",
     "Luchador Agent", "¡Olé! Type your message or /help and step into the ring!",
     "¡Adiós! Stay masked!",
     "✪", ["pinning opponents", "flying off the ropes", "wrestling", "training in the ring", "masking up"],
     "#DC2626", "#FACC15", "#F97316", "#120808", "#F7E9E9", "Cartoon Cartoons & Classics", "MUCHA LUCHA"),

    ("the-problem-solverz", "The Problem Solverz", "Neon-soaked adventures with Alfe, Robo and Horace.",
     "Problem Solver Agent", "We can solve it! Type your message or /help.",
     "Problem solved! Later!",
     "⚡", ["solving problems", "dealing with it", "going neon", "helping the city", "being rad"],
     "#E879F9", "#22D3EE", "#FDE047", "#140820", "#F6EAF9", "Cartoon Cartoons & Classics", "PROBLEM SOLVERZ"),

    ("out-of-jimmys-head", "Out of Jimmy's Head", "Live-action and cartoon — whatever Jimmy imagines, gets out.",
     "Jimmy Agent", "Watch your head! Type your message or /help.",
     "Imagination out! Bye!",
     "◎", ["imagining", "escaping the blob", "mixing cartoons", "daydreaming", "making a mess"],
     "#4ADE80", "#22D3EE", "#FDE047", "#081409", "#E9F7EB", "Cartoon Cartoons & Classics", "JIMMYS HEAD"),

    ("chowder", "Chowder", "An apprentice chef with a big appetite and a bigger imagination.",
     "Chowder Agent", "Mung Daal's kitchen open! Type your message or /help, apprentice.",
     "All full! See you at the next meal!",
     "☕", ["cooking up", "tasting the food", "snacking", "following recipes", "learning from Mung Daal"],
     "#A855F7", "#4ADE80", "#FB923C", "#120A18", "#F4ECF8", "Cartoon Cartoons & Classics", "CHOWDER"),

    ("flapjack", "The Marvelous Misadventures of Flapjack", "A boy and a pirate captain searching for Candied Island.",
     "Captain Flapjack Agent", "Ahoy, matey! Type your message or /help and set sail!",
     "Candied Island awaits! Goodbye!",
     "⚓", ["sailing for Candied Island", "craving candy", "escaping Captain K'nuckles' lies", "swabbing the deck", "talking to Bubbie"],
     "#2DD4BF", "#F87171", "#FDE047", "#071614", "#E5F6F4", "Cartoon Cartoons & Classics", "FLAPJACK"),

    ("total-drama", "Total Drama", "Reality TV satire — 22 campers, one island, zero mercy.",
     "Total Drama Agent", "Welcome to Total Drama! Type your message or /help... and good luck.",
     "And... you're eliminated! Bye!",
     "▶", ["eliminating contestants", "filming drama", "surviving challenges", "voting people off", "betraying allies"],
     "#22C55E", "#EF4444", "#FDE047", "#0A140C", "#EAF7EE", "Cartoon Cartoons & Classics", "TOTAL DRAMA"),

    ("total-dramarama", "Total DramaRama", "The Total Drama cast as chaotic toddlers.",
     "DramaRama Agent", "Nap time? No way! Type your message or /help!",
     "Snack time's over. Bye!",
     "☻", ["naptime", "snack time", "being toddlers", "causing chaos", "avoiding the daycare"],
     "#F472B6", "#38BDF8", "#FACC15", "#150A14", "#F9EAF4", "Cartoon Cartoons & Classics", "DRAMARAMA"),

    ("6teen", "6teen", "Six teens working and hanging out at the Galleria mall.",
     "Mall Agent", "The mall is open! Type your message or /help.",
     "Mall's closing! See you tomorrow!",
     "♡", ["hanging at the mall", "working retail", "avoiding the manager", "shopping", "meeting at the food court"],
     "#F472B6", "#60A5FA", "#FDE047", "#140A12", "#F8EAF2", "Cartoon Cartoons & Classics", "6TEEN"),

    ("stoked", "Stoked", "Six teens working a summer at a surf resort.",
     "Surf Agent", "Catch a wave! Type your message or /help, dude.",
     "Sun's down. See you on the beach!",
     "≋", ["catching waves", "shredding", "working the resort", "surfing", "hanging at the beach"],
     "#FB923C", "#2DD4BF", "#FDE047", "#120C06", "#F7EEE4", "Cartoon Cartoons & Classics", "STOKED"),

    ("robotboy", "Robotboy", "A top-secret battle robot living with a normal family.",
     "Robotboy Agent", "Super activation! Type your message or /help, pal.",
     "Powering down. Goodbye!",
     "⬢", ["powering up", "destroying targets", "protecting Gus", "charging up", "going super"],
     "#3B82F6", "#9CA3AF", "#FACC15", "#070D16", "#E4EAF5", "Cartoon Cartoons & Classics", "ROBOTBOY"),

    ("megas-xlr", "Megas XLR", "A giant robot from the future, a slacker driver and a mechanic.",
     "Megas Agent", "Coop's in the driver's seat! Type your message or /help.",
     "Megas shutting down. See ya!",
     "⚙", ["crushing the Klag", "repairing the giant robot", "driving Megas", "blasting enemies", "ordering takeout"],
     "#DC2626", "#9CA3AF", "#FDE047", "#120808", "#F7E9E9", "Cartoon Cartoons & Classics", "MEGAS XLR"),

    ("xiaolin-showdown", "Xiaolin Showdown", "Monk warriors collecting Shen Gong Wu artifacts.",
     "Xiaolin Agent", "Shen Gong Wu detected! Type your message or /help.",
     "Wu secured. Goodbye, monk!",
     "☯", ["finding Shen Gong Wu", "chasing Jack Spicer", "training in kung fu", "showdown-ing", "balancing the elements"],
     "#F59E0B", "#DC2626", "#FDE047", "#120C04", "#F8F0E2", "Cartoon Cartoons & Classics", "XIAOLIN"),

    ("secret-saturdays", "The Secret Saturdays", "A cryptozoologist family hunting legendary creatures.",
     "Cryptid Agent", "Cryptids sighted! Type your message or /help.",
     "Creature secured. Secret Saturdays out!",
     "✦", ["hunting cryptids", "tracking Kur", "studying legends", "protecting the family", "going on expeditions"],
     "#14B8A6", "#D97706", "#FDE047", "#071412", "#E3F4F2", "Cartoon Cartoons & Classics", "SECRET SATURDAYS"),

    ("sym-bionic-titan", "Sym-Bionic Titan", "Three alien teens pilot a giant mech to defend Earth.",
     "Titan Agent", "Sym-Bionic online! Type your message or /help.",
     "Titan disengaged. Stay strong!",
     "⬡", ["suiting up", "defending Earth", "piloting the Titan", "hiding in plain sight", "fighting Mutraddi"],
     "#3B82F6", "#F59E0B", "#FDE047", "#080E18", "#E6EDF7", "Cartoon Cartoons & Classics", "SYM-BIONIC"),

    ("hero-108", "Hero: 108", "Hidden Valley's secret animal army faces the HighRollers.",
     "Hero 108 Agent", "Heroes assemble! Type your message or /help.",
     "Hidden Valley is safe. Goodbye!",
     "✳", ["rounding up the animals", "defending Hidden Valley", "launching first strike", "training the army", "outsmarting the HighRollers"],
     "#F97316", "#84CC16", "#FDE047", "#120B04", "#F7EEE3", "Cartoon Cartoons & Classics", "HERO 108"),

    ("chop-socky-chooks", "Chop Socky Chooks", "Three kung-fu chickens defending their fish-and-chip shop.",
     "Chop Socky Agent", "Kung fu chickens ready! Type your message or /help!",
     "Wok's closed! Bye!",
     "✚", ["kung-fu fighting", "clucking chaos", "defending the shop", "kicking butt", "being awesome"],
     "#EF4444", "#F8FAFC", "#FACC15", "#120606", "#F9E9E9", "Cartoon Cartoons & Classics", "CHOP SOCKY"),

    ("skatoony", "Skatoony", "Skateboarding quiz show — answer or wipe out!",
     "Skatoony Agent", "Welcome to Skatoony! Type your message or /help... or wipe out!",
     "That's the show! Stay on your board!",
     "✹", ["skating along", "answering trivia", "wiping out", "hitting the ramps", "competing"],
     "#F97316", "#3B82F6", "#FDE047", "#120B05", "#F7EEE3", "Cartoon Cartoons & Classics", "SKATOONY"),

    ("hot-wheels-battle-force-5", "Hot Wheels Battle Force 5", "Racing cars with weapons, defending Earth from the Sark.",
     "Battle Force Agent", "Engines roaring! Type your message or /help, driver.",
     "Garage closing! See you at the next race!",
     "➤", ["racing", "battling the Sark", "transforming the cars", "driving fast", "saving Earth"],
     "#DC2626", "#3B82F6", "#FDE047", "#100808", "#F6E9E9", "Cartoon Cartoons & Classics", "BATTLE FORCE 5"),

    ("monster-beach", "Monster Beach", "Surfing monsters living at the graveyard shore.",
     "Monster Agent", "Welcome to the graveyard shore! Type your message or /help.",
     "Night's over! Catch you at the next wave!",
     "☾", ["surfing the graveyard shore", "scaring tourists", "hanging with the undead", "catching waves", "avoiding daylight"],
     "#A855F7", "#4ADE80", "#FDE047", "#0E0814", "#F2ECF8", "Cartoon Cartoons & Classics", "MONSTER BEACH"),

    ("ducks-dodgers", "Duck Dodgers", "Daffy Duck as the 24th-and-a-half-century space hero.",
     "Duck Dodgers Agent", "Duck Dodgers reporting for duty! Type your message or /help.",
     "Mission accomplished... probably. Bye!",
     "✧", ["quacking off", "outsmarting Marvin", "saving the galaxy", "avoiding Kangaroo Kasey", "being a hero (sort of)"],
     "#3B82F6", "#FACC15", "#FDE047", "#070D16", "#E6EDF7", "Cartoon Cartoons & Classics", "DUCK DODGERS"),

    ("loonatics-unleashed", "Loonatics Unleashed", "Futuristic descendants of the Looney Tunes saving Metropolis.",
     "Loonatic Agent", "Loonatics on the job! Type your message or /help.",
     "Metropolis is safe. Acme out!",
     "✵", ["acme-ing", "saving Metropolis 2771", "fighting crime", "zapping villains", "being super"],
     "#94A3B8", "#2DD4BF", "#FDE047", "#0E1013", "#ECEEF1", "Cartoon Cartoons & Classics", "LOONATICS"),

    ("baby-looney-tunes", "Baby Looney Tunes", "The classic characters as toddlers in daycare.",
     "Baby Toon Agent", "Hiya, baby! Type your message or /help!",
     "Naptime! Bye-bye!",
     "✽", ["napping", "crawling around", "playing with toys", "going to daycare", "making a mess"],
     "#F9A8D4", "#93C5FD", "#FDE68A", "#140B12", "#F9ECF4", "Cartoon Cartoons & Classics", "BABY TUNES"),

    ("krypto-superdog", "Krypto the Superdog", "Superman's dog protecting Metropolis as a family pet.",
     "Krypto Agent", "Superdog on duty! Type your message or /help!",
     "Time for a doggie treat. Bye!",
     "☉", ["fetching villains", "super-barking", "flying", "protecting the family", "fighting cat crime"],
     "#3B82F6", "#EF4444", "#FACC15", "#070E18", "#E7EEF7", "Cartoon Cartoons & Classics", "KRYPTO"),

    # ---------------- Modern Cartoon Network ----------------
    ("adventure-time", "Adventure Time", "Finn and Jake's mathematical quests across the Land of Ooo.",
     "Adventure Agent", "Adventure time! Type your message or /help, dude!",
     "Mathematical! See you in Ooo!",
     "❄", ["adventuring", "counting math", "saving Ooo", "exploring dungeons", "hanging with Jake"],
     "#4FC3F7", "#FDE047", "#F472B6", "#0A1218", "#E8F2F8", "Modern Cartoon Network", "ADVENTURE TIME"),

    ("regular-show", "Regular Show", "Mordecai and Rigby's very regular, very weird park jobs.",
     "Park Agent", "Ooooh! Type your message or /help, dude.",
     "Alright, time to clock out. Later!",
     "☰", ["slacking off", "playing video games", "working at the park", "escaping death", "ordering slushies"],
     "#3B82F6", "#4ADE80", "#FDE047", "#080F18", "#E7EEF7", "Modern Cartoon Network", "REGULAR SHOW"),

    ("the-amazing-world-of-gumball", "The Amazing World of Gumball", "A blue cat and a goldfish navigating Elmore's chaos.",
     "Elmore Agent", "Welcome to Elmore! Type your message or /help, dummy.",
     "See you at school tomorrow!",
     "◉", ["surviving Elmore", "talking to the family", "outsmarting Darwin", "getting detention", "chaos-ing"],
     "#F472B6", "#38BDF8", "#A3E635", "#130A12", "#F8EBF3", "Modern Cartoon Network", "GUMBALL"),

    ("steven-universe", "Steven Universe", "A half-gem boy learning to protect Beach City with the Crystal Gems.",
     "Crystal Gem Agent", "We are the Crystal Gems! Type your message or /help.",
     "If every pork chop were perfect... goodbye!",
     "★", ["fusing", "singing", "protecting Beach City", "learning to be a gem", "eating cookie cats"],
     "#F9A8D4", "#93C5FD", "#FDE047", "#120A12", "#FAEDF4", "Modern Cartoon Network", "STEVEN"),

    ("we-bare-bears", "We Bare Bears", "Grizz, Panda and Ice Bear trying to fit in with humans.",
     "Bear Agent", "Hey, we're the bears! Type your message or /help.",
     "Time to hibernate. Bye!",
     "☃", ["being brothers", "ordering food", "chilling", "trying to fit in", "hiking"],
     "#FB923C", "#60A5FA", "#22D3EE", "#100B06", "#F7EFE5", "Modern Cartoon Network", "BARE BEARS"),

    ("we-baby-bears", "We Baby Bears", "The baby bears' adventures through magical portals.",
     "Baby Bear Agent", "Baby bears on the move! Type your message or /help!",
     "Portal's closing! Bye-bye!",
     "❅", ["baby stuff", "exploring", "going through portals", "making friends", "getting snacks"],
     "#FDBA74", "#93C5FD", "#F9A8D4", "#120C08", "#F9F1E8", "Modern Cartoon Network", "BABY BEARS"),

    ("uncle-grandpa", "Uncle Grandpa", "Everyone's magical uncle and grandpa who only exists to help.",
     "Uncle Grandpa Agent", "Good morning! Type your message or /help, nephew!",
     "Good night! See you tomorrow!",
     "☀", ["good morning-ing", "uncle-ing", "helping kids", "driving the RV", "being magical"],
     "#F472B6", "#38BDF8", "#A3E635", "#140A14", "#FAECF4", "Modern Cartoon Network", "UNCLE GRANDPA"),

    ("clarence", "Clarence", "A relentlessly sunny kid and his friends in Aberdale.",
     "Clarence Agent", "Woo! Type your message or /help, buddy!",
     "Sun's going down. See ya!",
     "☼", ["playing outside", "being sunny", "making friends", "exploring Aberdale", "having fun"],
     "#FACC15", "#38BDF8", "#FB923C", "#121008", "#F9F5E8", "Modern Cartoon Network", "CLARENCE"),

    ("craig-of-the-creek", "Craig of the Creek", "Craig and his crew exploring the kid-ruled creek.",
     "Creek Agent", "Welcome to the creek! Type your message or /help, creek kid.",
     "Creek's closing at sunset. Later!",
     "⚑", ["exploring the creek", "leading the creek kids", "finding treasure", "making maps", "surviving the creek"],
     "#14B8A6", "#FB923C", "#FDE047", "#071512", "#E6F5F2", "Modern Cartoon Network", "CRAIG"),

    ("ok-ko", "OK K.O.! Let's Be Heroes", "K.O. trains to be a hero at Lakewood Plaza Turbo.",
     "Hero Agent", "Let's be heroes! Type your message or /help!",
     "Powering down. Be a hero!",
     "✴", ["powering up", "punching robots", "being a hero", "training at the plaza", "leveling up"],
     "#EF4444", "#3B82F6", "#FDE047", "#110707", "#F8E9E9", "Modern Cartoon Network", "OK K.O."),

    ("infinity-train", "Infinity Train", "Passengers ride an endless train solving their personal issues.",
     "Train Agent", "Welcome aboard the Infinity Train. Type your message or /help.",
     "End of the line... for now.",
     "✱", ["riding the train", "facing the numbers", "solving the mystery", "meeting the passengers", "finding the exit"],
     "#FB923C", "#A855F7", "#FDE047", "#100B06", "#F7EFE5", "Modern Cartoon Network", "INFINITY TRAIN"),

    ("apple-onion", "Apple & Onion", "Two food friends chasing their dreams in the big city.",
     "Apple Agent", "Hey! Type your message or /help, pal!",
     "Gotta go make pancakes. Later!",
     "✢", ["making pancakes", "jamming in the city", "being friends", "chasing dreams", "eating snacks"],
     "#F97316", "#4ADE80", "#FDE047", "#100B04", "#F8F0E6", "Modern Cartoon Network", "APPLE & ONION"),

    ("victor-valentino", "Victor and Valentino", "Two brothers exploring a Mexican folklore town.",
     "Monte Macabre Agent", "Welcome to Monte Macabre! Type your message or /help.",
     "Folklore's done for today. Bye!",
     "☾", ["chasing chupacabras", "hanging in Monte Macabre", "messing with the gods", "exploring folklore", "avoiding Grandma"],
     "#A855F7", "#FB923C", "#FDE047", "#0F0814", "#F3EDF8", "Modern Cartoon Network", "VICTOR VALENTINO"),

    ("mao-mao", "Mao Mao: Heroes of Pure Heart", "A hot-tempered sheriff cat defending Pure Heart Valley.",
     "Sheriff Agent", "Pure Heart Valley protected! Type your message or /help!",
     "Sheriff Mao Mao out! Stay pure of heart!",
     "✕", ["defending Pure Heart Valley", "riding King Snugglemagne", "patrolling", "hunting the Sky Pirates", "being a hero"],
     "#F97316", "#A855F7", "#FDE047", "#100B05", "#F7EFE5", "Modern Cartoon Network", "MAO MAO"),

    ("summer-camp-island", "Summer Camp Island", "A magical summer camp where nothing is quite normal.",
     "Camp Agent", "Welcome to Summer Camp Island! Type your message or /help.",
     "See you next summer!",
     "✾", ["sending signals", "enjoying camp", "meeting magical friends", "exploring the island", "making s'mores"],
     "#67E8F9", "#F9A8D4", "#FDE68A", "#0A1418", "#E9F6F8", "Modern Cartoon Network", "CAMP ISLAND"),

    ("elliott-from-earth", "Elliott from Earth", "A boy, his mom and a dinosaur stranded on Earth.",
     "Elliott Agent", "Welcome to Earth! Type your message or /help, alien.",
     "Mission on Earth complete. Bye!",
     "✷", ["exploring Earth", "learning human things", "hanging with the dinosaur", "going on adventures", "discovering the world"],
     "#2DD4BF", "#A855F7", "#FDE047", "#071516", "#E7F6F5", "Modern Cartoon Network", "ELLIOTT"),

    ("mighty-magiswords", "Mighty Magiswords", "Prohyas and Vambre collect magical swords for quests.",
     "Magiswords Agent", "Magiswords ready! Type your message or /help, adventurer!",
     "Quest complete! Magiswords out!",
     "❋", ["wielding magiswords", "dungeon crawling", "collecting swords", "going on quests", "solving riddles"],
     "#84CC16", "#A855F7", "#FDE047", "#0C1406", "#F1F7E8", "Modern Cartoon Network", "MAGISWORDS"),

    ("annoying-orange", "The High Fructose Adventures of Annoying Orange", "The obnoxious fruit that never stops talking.",
     "Orange Agent", "HEY APPLE! Type your message or /help... or don't. HEY!",
     "Okay, bye! Wait, come back! HEY!",
     "❍", ["asking annoying questions", "dodging the knife", "yelling at fruit", "talking nonstop", "telling puns"],
     "#FB923C", "#FDE047", "#4ADE80", "#0F0A04", "#F8F0E6", "Modern Cartoon Network", "ANNOYING ORANGE"),

    ("teen-titans-go", "Teen Titans Go!", "The Titans' silly, snack-fueled side adventures.",
     "Titan Agent", "Titans, GO! Type your message or /help!",
     "Titans, stop! See ya!",
     "♯", ["silly heroing", "fighting over pizza", "singing songs", "arguing", "going to the movies"],
     "#8B5CF6", "#38BDF8", "#FDE047", "#0C0914", "#F1ECF8", "Modern Cartoon Network", "TITANS GO"),

    ("jade-armor", "Jade Armor", "A teen girl discovers a legendary jade armor.",
     "Jade Agent", "Jade armor, activate! Type your message or /help!",
     "Armor deactivated. Stay strong!",
     "◈", ["powering up the jade armor", "protecting the city", "training the dragon", "fighting evil", "being a hero"],
     "#10B981", "#F59E0B", "#FDE047", "#05120C", "#E7F5EE", "Modern Cartoon Network", "JADE ARMOR"),

    ("unikitty", "Unikitty", "The LEGO princess of rage and happiness in Unikittyland.",
     "Unikitty Agent", "Unikittyland welcomes you! Type your message or /help!",
     "Bye-bye! Stay sparkly!",
     "❀", ["being sparkly", "getting angry", "having fun", "dealing with Master Frown", "party-ing"],
     "#F472B6", "#FDE047", "#38BDF8", "#140A12", "#F9EBF3", "Modern Cartoon Network", "UNIKITTY"),

    ("mixels", "Mixels", "Mix and match creatures from the Nixel-infested Mixel world.",
     "Mix Agent", "Mixels, mix! Type your message or /help!",
     "Unmix! Goodbye!",
     "◼", ["mixing", "building combos", "fighting Nixels", "combining powers", "creating new mixes"],
     "#FB923C", "#3B82F6", "#FDE047", "#0F0A04", "#F7EFE5", "Modern Cartoon Network", "MIXELS"),

    ("thundercats-roar", "ThunderCats Roar", "The goofy 2019 reboot of the classic cat heroes.",
     "ThunderCat Agent", "ThunderCats, ho! Type your message or /help!",
     "ThunderCats out! Hoooo!",
     "☇", ["summoning the sword", "being silly", "fighting Mumm-Ra", "roaring", "having cat adventures"],
     "#F97316", "#60A5FA", "#FDE047", "#0F0904", "#F7EFE5", "Modern Cartoon Network", "THUNDERCATS"),

    ("dreamworks-dragons", "DreamWorks Dragons", "Hiccup and Toothless' adventures from the Dragon franchise.",
     "Dragon Agent", "Ready to fly! Type your message or /help, dragon rider.",
     "Toothless is sleepy. Goodnight!",
     "☄", ["training dragons", "flying with Toothless", "defending Berk", "learning dragon lore", "riding the wind"],
     "#EF4444", "#F59E0B", "#38BDF8", "#100606", "#F7E9E9", "Modern Cartoon Network", "DRAGONS"),

    # ---------------- DC Super Heroes ----------------
    ("teen-titans", "Teen Titans", "The classic Titans — Robin, Starfire, Raven, Cyborg and Beast Boy.",
     "Titan Agent", "Titans together! Type your message or /help, hero.",
     "Titans out!",
     "✖", ["assemble-ing", "fighting Slade", "training at the tower", "going on missions", "protecting Jump City"],
     "#DC2626", "#6B7280", "#F87171", "#0F0505", "#F6E9E9", "DC Super Heroes", "TEEN TITANS"),

    ("justice-league", "Justice League", "Earth's mightiest heroes united as one team.",
     "League Agent", "Justice League assembled! Type your message or /help.",
     "League adjourned. The watchtower is watching.",
     "◆", ["assembling the league", "saving the world", "patrolling the watchtower", "fighting Darkseid", "answering the signal"],
     "#2563EB", "#F59E0B", "#FDE047", "#070D18", "#E5ECF7", "DC Super Heroes", "JUSTICE LEAGUE"),

    ("justice-league-unlimited", "Justice League Unlimited", "The expanded league with dozens of heroes in action.",
     "League Agent", "League expanded. Type your message or /help, hero.",
     "Unlimited heroes, one mission. Out.",
     "✶", ["expanding the league", "coordinating heroes", "fighting Cadmus", "saving the planet", "deploying teams"],
     "#1D4ED8", "#F59E0B", "#93C5FD", "#060C16", "#E4EBF6", "DC Super Heroes", "JUSTICE LEAGUE"),

    ("batman-tas", "Batman: The Animated Series", "The Dark Knight of Gotham in the definitive animated take.",
     "Batman Agent", "I'm Batman. Type your message or /help.",
     "The night is over. Gotham sleeps.",
     "☾", ["patrolling Gotham", "striking from the shadows", "fighting the rogues", "protecting the city", "being the night"],
     "#334155", "#FACC15", "#94A3B8", "#05070B", "#E6EAF0", "DC Super Heroes", "BATMAN"),

    ("batman-beyond", "Batman Beyond", "A teenager inherits the Batsuit in Neo-Gotham.",
     "Batman Agent", "I'm Batman... the new one. Type your message or /help.",
     "Suit off. Later, old man.",
     "⚡", ["gliding across Neo-Gotham", "hacking the suit", "fighting Inque", "learning from Bruce", "being the new Batman"],
     "#DC2626", "#38BDF8", "#FACC15", "#0D0406", "#F6E7E8", "DC Super Heroes", "BATMAN BEYOND"),

    ("static-shock", "Static Shock", "Virgil Hawkins — the electric superhero of Dakota.",
     "Static Agent", "Static's got it! Type your message or /help.",
     "Shocking out! Later, Dakota!",
     "☇", ["shocking villains", "riding the static", "protecting Dakota", "fighting the Meta-Breed", "school-ing villains"],
     "#FACC15", "#3B82F6", "#FDE047", "#100E04", "#F9F6E6", "DC Super Heroes", "STATIC SHOCK"),

    ("zeta-project", "The Zeta Project", "A prototype spy robot trying to prove he's not a weapon.",
     "Zeta Agent", "Zeta online. Type your message or /help, Ro.",
     "Going dark. Zeta out.",
     "⌖", ["going undercover", "evading capture", "helping people", "proving he's not a weapon", "hiding from the NSA"],
     "#64748B", "#22D3EE", "#FDE047", "#0B0D10", "#EBEDF0", "DC Super Heroes", "ZETA PROJECT"),

    ("young-justice", "Young Justice", "The teen sidekicks operating as a covert team.",
     "Young Justice Agent", "Covert ops online. Type your message or /help, teammate.",
     "Mission complete. Back to the mountain.",
     "✯", ["going covert", "training at the mountain", "going undercover", "taking down the Light", "protecting the world"],
     "#DC2626", "#94A3B8", "#F87171", "#0D0505", "#F6E9E9", "DC Super Heroes", "YOUNG JUSTICE"),

    ("green-lantern-tas", "Green Lantern: The Animated Series", "Hal Jordan and Kilowog patrolling the universe.",
     "Lantern Agent", "In brightest day... Type your message or /help.",
     "In blackest night... goodnight!",
     "⦿", ["constructing constructs", "patrolling Sector 2814", "fighting the Red Lanterns", "protecting the universe", "charging the ring"],
     "#22C55E", "#86EFAC", "#FDE047", "#050D08", "#E7F5EB", "DC Super Heroes", "GREEN LANTERN"),

    ("beware-the-batman", "Beware the Batman", "The 2013 Batman series focused on Detective Gordon and Katana.",
     "Batman Agent", "Gotham needs me. Type your message or /help.",
     "Gotham is safe tonight.",
     "✹", ["interrogating", "dismantling the cabal", "fighting assassins", "working with Katana", "protecting Gotham"],
     "#475569", "#DC2626", "#FACC15", "#08090C", "#E9EBEE", "DC Super Heroes", "BATMAN 2013"),

    ("justice-league-action", "Justice League Action", "Fast-paced, fun-sized league adventures.",
     "League Agent", "League, action! Type your message or /help!",
     "Action over! See you next episode!",
     "❯", ["taking action", "saving the day", "teaming up", "fighting villains", "being quick"],
     "#3B82F6", "#EF4444", "#FDE047", "#070E18", "#E6EDF7", "DC Super Heroes", "LEAGUE ACTION"),

    ("dc-super-hero-girls", "DC Super Hero Girls", "Super-powered teens balancing heroics and high school.",
     "Hero Girl Agent", "Super Hero High! Type your message or /help, classmate!",
     "School's out! Save the day tomorrow!",
     "✺", ["going to school", "fighting super villains", "studying heroics", "hanging with the team", "saving Metropolis"],
     "#F472B6", "#3B82F6", "#FDE047", "#110A14", "#F8EBF3", "DC Super Heroes", "HERO GIRLS"),

    ("batman-brave-bold", "Batman: The Brave and the Bold", "Batman teaming up with heroes across the DC universe.",
     "Batman Agent", "The Brave and the Bold! Type your message or /help, partner.",
     "Case closed, partner. Out!",
     "✭", ["teaming up with heroes", "cracking jokes", "fighting villains", "answering the signal", "saving the day"],
     "#B45309", "#E5E7EB", "#FACC15", "#0C0803", "#F3EEE4", "DC Super Heroes", "BRAVE & BOLD"),
]
