# -*- coding: utf-8 -*-
"""Cartoon Network skin database, part 2.

Same field order as shows_data1.py:
slug, title, desc, agent, welcome, goodbye, sym, verbs, p, s, a, bg, tx, cat, logo
"""

SHOWS_B = [
    # ---------------- Star Wars & LEGO ----------------
    ("star-wars-clone-wars", "Star Wars: The Clone Wars", "Anakin, Obi-Wan and the clones in the Clone Wars era.",
     "Republic Agent", "For the Republic! Type your message or /help, commander.",
     "The Republic is safe. May the Force be with you.",
     "✸", ["deploying clones", "fighting the Separatists", "defending the Republic", "piloting starfighters", "training Jedi"],
     "#1D4ED8", "#93C5FD", "#FDE047", "#050A14", "#E3EBF7", "Star Wars & LEGO", "CLONE WARS"),

    ("ninjago", "Ninjago: Masters of Spinjitzu", "Elemental ninja protect Ninjago from the forces of darkness.",
     "Ninja Agent", "Ninja-Go! Type your message or /help, ninja.",
     "The balance is restored. Ninja out!",
     "✹", ["spinjitzu-ing", "protecting Ninjago", "training at the monastery", "fighting the Serpentine", "unlocking elemental powers"],
     "#DC2626", "#2563EB", "#84CC16", "#0D0507", "#F6E9E9", "Star Wars & LEGO", "NINJAGO"),

    ("lego-monkie-kid", "LEGO Monkie Kid", "MK wields the Monkey King's staff against demons.",
     "Monkie Agent", "Monkie Kid on the scene! Type your message or /help!",
     "The journey continues! Bye!",
     "☯", ["wielding the staff", "fighting demons", "riding the cloud", "training with Monkey King", "protecting the city"],
     "#F97316", "#F59E0B", "#FDE047", "#0F0A04", "#F7F0E6", "Star Wars & LEGO", "MONKIE KID"),

    ("lego-city-adventures", "LEGO City Adventures", "Everyday heroes of LEGO City — cops, firefighters and more.",
     "City Agent", "LEGO City at your service! Type your message or /help.",
     "City safe! Building complete!",
     "✈", ["going on city adventures", "driving the fire truck", "catching crooks", "building things", "helping the citizens"],
     "#3B82F6", "#F8FAFC", "#FDE047", "#07101C", "#E7EEF8", "Star Wars & LEGO", "LEGO CITY"),

    ("thundercats-2011", "ThunderCats (2011)", "Lion-O and the ThunderCats rebuild after Thundera's fall.",
     "ThunderCat Agent", "ThunderCats, ho! Type your message or /help!",
     "ThunderCats out! Third Earth is safe!",
     "✰", ["summoning the Sword of Omens", "defending Thundera", "training with the cats", "fighting Mumm-Ra", "hunting the Book of Omens"],
     "#DC2626", "#3B82F6", "#FACC15", "#0E0505", "#F6E9E9", "Star Wars & LEGO", "THUNDERCATS"),

    # ---------------- Toonami & Action ----------------
    ("toonami", "Toonami", "The legendary action block — TOM's late-night anime lineup.",
     "Toonami Agent", "Toonami is here! Type your message or /help and stay tuned.",
     "Toonami out. The night continues!",
     "▸", ["powering up", "continuing the night", "airing the lineup", "booting the system", "staying after midnight"],
     "#F97316", "#3B82F6", "#FDE047", "#0F0A05", "#F7EFE5", "Toonami & Action", "TOONAMI"),

    ("dragon-ball-z", "Dragon Ball Z", "Goku and the Z-Fighters defending Earth from planet-level threats.",
     "Z-Fighter Agent", "Power level over 9000! Type your message or /help!",
     "Earth is safe. See you in the next saga!",
     "☄", ["charging the Kamehameha", "going Super Saiyan", "powering up", "training in the Hyperbolic Time Chamber", "fighting Frieza"],
     "#F97316", "#3B82F6", "#FDE047", "#0F0904", "#F7EFE5", "Toonami & Action", "DRAGON BALL Z"),

    ("dragon-ball-gt", "Dragon Ball GT", "Goku shrunk to a kid, searching the Black Star Dragon Balls.",
     "GT Agent", "Dragon Ball GT online! Type your message or /help!",
     "The Dragon Balls are safe. Later!",
     "☀", ["searching the Black Star Balls", "going Golden Oozaru", "flying around the galaxy", "collecting Dragon Balls", "fighting Baby"],
     "#DC2626", "#FACC15", "#FDE047", "#0E0505", "#F6E9E9", "Toonami & Action", "DRAGON BALL GT"),

    ("dragon-ball-super", "Dragon Ball Super", "Gods of Destruction, tournaments and Ultra Instinct.",
     "Super Agent", "Dragon Ball Super! Type your message or /help!",
     "Tournament over! See you at the next universe!",
     "⭘", ["mastering Ultra Instinct", "training with Whis", "fighting gods", "entering tournaments", "pushing past limits"],
     "#DC2626", "#38BDF8", "#A3E635", "#0D0406", "#F7E9E9", "Toonami & Action", "DRAGON BALL SUPER"),

    ("naruto", "Naruto", "A loud ninja with a dream of becoming Hokage.",
     "Ninja Agent", "Believe it! Type your message or /help, ninja!",
     "That's my ninja way! Later!",
     "❂", ["training with shadow clones", "becoming Hokage", "learning jutsu", "eating ramen", "never giving up"],
     "#F97316", "#2563EB", "#FDE047", "#0F0904", "#F7EFE5", "Toonami & Action", "NARUTO"),

    ("naruto-shippuden", "Naruto Shippuden", "Naruto's older, darker journey to bring Sasuke home.",
     "Hokage Agent", "Shippuden online! Type your message or /help.",
     "The war is over. Believe it!",
     "✽", ["chasing Sasuke", "unleashing the Nine Tails", "mastering Sage Mode", "protecting the village", "ending the war"],
     "#DC2626", "#F87171", "#FDE047", "#0D0405", "#F6E8E8", "Toonami & Action", "SHIPPUDEN"),

    ("one-piece", "One Piece", "Monkey D. Luffy's quest for the One Piece and the Pirate King title.",
     "Pirate Agent", "The straw hat crew is here! Type your message or /help!",
     "Sailed off! The adventure continues!",
     "☠", ["sailing the Grand Line", "becoming Pirate King", "stretching for victory", "finding the One Piece", "battling the Marines"],
     "#DC2626", "#FACC15", "#FDE047", "#0F0505", "#F7E9E9", "Toonami & Action", "ONE PIECE"),

    ("bleach", "Bleach", "Ichigo Kurosaki, the substitute Soul Reaper.",
     "Soul Reaper Agent", "Bankai! Type your message or /help, Soul Reaper.",
     "The hollows are gone. Later!",
     "✚", ["releasing Bankai", "fighting hollows", "training in the Soul Society", "protecting Karakura", "mastering the Zanpakutō"],
     "#E5E7EB", "#EF4444", "#FDE047", "#0D0E10", "#EDEFF2", "Toonami & Action", "BLEACH"),

    ("cowboy-bebop", "Cowboy Bebop", "Bounty hunters in space, jazz in the background.",
     "Bebop Agent", "See you, space cowboy. Type your message or /help.",
     "Whatever happens, happens. Later!",
     "♪", ["hunting bounties", "jamming with the Bebop crew", "flying the Swordfish", "tracking targets", "eating bell peppers and beef"],
     "#3B82F6", "#DC2626", "#FDE047", "#070D16", "#E5ECF7", "Toonami & Action", "COWBOY BEBOP"),

    ("samurai-champloo", "Samurai Champloo", "Hip-hop samurai road trip across Edo Japan.",
     "Champloo Agent", "Let's get this bread, samurai. Type your message or /help.",
     "The sunflower samurai awaits. Later!",
     "✶", ["samurai-ing", "finding the sunflower samurai", "battling in Edo", "flipping blades", "going on the road"],
     "#F97316", "#D97706", "#FDE047", "#100903", "#F7EFE4", "Toonami & Action", "CHAMPLOO"),

    ("eureka-seven", "Eureka Seven", "Renton pilots the Nirvash and rides the trapar waves.",
     "Renton Agent", "Surf's up! Type your message or /help, pilot.",
     "The waves are calm. Later!",
     "✦", ["riding the trapar waves", "piloting the Nirvash", "joining Gekkostate", "skateboarding", "saving Eureka"],
     "#3B82F6", "#F8FAFC", "#FDE047", "#060D18", "#E5EDF8", "Toonami & Action", "EUREKA 7"),

    ("inuyasha", "Inuyasha", "A half-demon and a schoolgirl hunting Shikon shards.",
     "Inuyasha Agent", "Sit, boy! Type your message or /help!",
     "The shards are sealed. Later!",
     "⛩", ["hunting shards", "purifying the jewel", "fighting Naraku", "sitting Inuyasha", "crossing the well"],
     "#A855F7", "#DC2626", "#FDE047", "#0D0714", "#F2ECF8", "Toonami & Action", "INUYASHA"),

    ("fullmetal-alchemist", "Fullmetal Alchemist", "Two brothers and the law of equivalent exchange.",
     "Alchemist Agent", "Equivalent exchange. Type your message or /help.",
     "The Philosopher's Stone quest continues.",
     "✜", ["transmuting", "seeking the Philosopher's Stone", "performing alchemy", "searching for answers", "fighting homunculi"],
     "#D97706", "#DC2626", "#FDE047", "#0D0803", "#F4EEE3", "Toonami & Action", "FULLMETAL"),

    ("yu-yu-hakusho", "Yu Yu Hakusho", "Spirit detective Yusuke fighting the demon world.",
     "Spirit Detective Agent", "Spirit gun charged! Type your message or /help, detective.",
     "Case closed. Later!",
     "✺", ["hunting demons", "fighting in the Dark Tournament", "charging the Spirit Gun", "protecting the living world", "working with the team"],
     "#3B82F6", "#4ADE80", "#FDE047", "#070E18", "#E6EDF7", "Toonami & Action", "YU YU HAKUSHO"),

    ("hunter-x-hunter", "Hunter x Hunter", "Gon and Killua take the Hunter Exam and master Nen.",
     "Hunter Agent", "Let's go hunting! Type your message or /help!",
     "The hunt continues! See you!",
     "⛏", ["hunting", "mastering Nen", "climbing the tower", "taking the Hunter Exam", "finding Ging"],
     "#22C55E", "#38BDF8", "#FDE047", "#05100A", "#E8F6EC", "Toonami & Action", "HUNTERXHUNTER"),

    ("attack-on-titan", "Attack on Titan", "Humanity fights for survival against the Titans.",
     "Scout Agent", "Dedicate your hearts! Type your message or /help, soldier.",
     "The walls stand. Fight on!",
     "✕", ["maneuvering with the ODM gear", "fighting titans", "scouting beyond the walls", "training with the corps", "fighting for humanity"],
     "#8B5A2B", "#DC2626", "#E5E7EB", "#0A0705", "#EFE9E2", "Toonami & Action", "TITAN"),

    ("my-hero-academia", "My Hero Academia", "Deku trains to become the greatest hero at UA.",
     "Hero Agent", "Plus Ultra! Type your message or /help, hero in training!",
     "Go beyond! Plus Ultra!",
     "✤", ["going Plus Ultra", "training One For All", "studying at UA", "saving people", "becoming a hero"],
     "#22C55E", "#EF4444", "#FDE047", "#05120B", "#E8F6ED", "Toonami & Action", "PLUS ULTRA"),

    ("jojo-bizarre-adventure", "JoJo's Bizarre Adventure", "Generations of Joestars and their Stands.",
     "JoJo Agent", "Yare yare daze. Type your message or /help.",
     "To be continued...",
     "✣", ["posing", "unleashing the Stand", "going Za Warudo", "fighting vampires", "the journey continues"],
     "#A855F7", "#FACC15", "#FDE047", "#0D0714", "#F2ECF8", "Toonami & Action", "JOJO"),

    ("mob-psycho-100", "Mob Psycho 100", "A powerful psychic trying to live an ordinary life.",
     "Mob Agent", "Counting to 100... Type your message or /help!",
     "100%. Goodbye!",
     "∞", ["counting to 100", "unleashing psychic energy", "working at the office", "controlling emotions", "reaching 100 percent"],
     "#2DD4BF", "#A855F7", "#FDE047", "#061514", "#E7F6F5", "Toonami & Action", "MOB PSYCHO 100"),

    ("demon-slayer", "Demon Slayer", "Tanjiro's quest to cure his sister and slay demons.",
     "Slayer Agent", "Total concentration! Type your message or /help, slayer!",
     "The demons are vanquished. Later!",
     "✷", ["breathing techniques", "slaying demons", "training with the Hashira", "protecting Nezuko", "hunting Muzan"],
     "#15803D", "#94A3B8", "#EF4444", "#04100A", "#E9F5EE", "Toonami & Action", "DEMON SLAYER"),

    ("sword-art-online", "Sword Art Online", "Players trapped in a deadly VRMMO must clear the game.",
     "SAO Agent", "Link start! Type your message or /help, player!",
     "Logging out. See you in the next world!",
     "✹", ["clearing the floor", "trapped in Aincrad", "dueling with swords", "leveling up", "surviving the game"],
     "#22D3EE", "#F8FAFC", "#FDE047", "#041218", "#E6F4F8", "Toonami & Action", "SWORD ART"),

    ("one-punch-man", "One Punch Man", "Saitama ends every fight with one punch.",
     "S-Class Agent", "OK! Type your message or /help... or one punch.",
     "One punch. Done. Goodbye!",
     "⊗", ["defeating everything in one punch", "training with Saitama", "hero-ing for fun", "battling monsters", "saving the city"],
     "#DC2626", "#FACC15", "#FDE047", "#0F0505", "#F7E9E9", "Toonami & Action", "ONE PUNCH MAN"),

    ("dr-stone", "Dr. Stone", "Senku rebuilds civilization from stone with science.",
     "Senku Agent", "Ten billion percent! Type your message or /help!",
     "Science is here! Let's build the future!",
     "⚛", ["reviving humanity", "inventing from scratch", "doing science", "building the kingdom", "measuring everything"],
     "#DC2626", "#F8FAFC", "#22D3EE", "#0C0404", "#F6E8E8", "Toonami & Action", "DR STONE"),

    ("fire-force", "Fire Force", "Special fire brigades fighting Infernals with flames.",
     "Fire Soldier Agent", "Ignition! Type your message or /help, soldier!",
     "Fire out! Company 8 reporting in!",
     "♨", ["igniting", "fighting the Infernals", "controlling flames", "training with Company 8", "saving civilians"],
     "#F97316", "#3B82F6", "#FDE047", "#0E0703", "#F7EFE5", "Toonami & Action", "FIRE FORCE"),

    ("gundam-wing", "Mobile Suit Gundam Wing", "Five Gundam pilots and their fight for the colonies.",
     "Gundam Pilot", "Gundam, launching! Type your message or /help, pilot.",
     "Mission complete. Returning to base.",
     "✥", ["launching", "defending the colonies", "piloting the Gundam", "fighting OZ", "going to space"],
     "#3B82F6", "#F8FAFC", "#FACC15", "#060D18", "#E5EDF8", "Toonami & Action", "GUNDAM WING"),

    ("gundam-00", "Mobile Suit Gundam 00", "Celestial Being intervenes to end war with Gundams.",
     "Gundam Agent", "GN drive online! Type your message or /help.",
     "Intervention complete. Setsuna out.",
     "✩", ["intervening", "bringing peace with the Gundams", "piloting the Exia", "fighting for change", "initiating the plan"],
     "#DC2626", "#FACC15", "#FDE047", "#0D0405", "#F6E8E8", "Toonami & Action", "GUNDAM 00"),

    ("space-dandy", "Space Dandy", "The dandy guy in space, hunting rare aliens.",
     "Dandy Agent", "Dandy, baby! Type your message or /help!",
     "See you, baby!",
     "❁", ["hunting rare aliens", "exploring the galaxy", "dodging the Gogol Empire", "being dandy", "finding new species"],
     "#F97316", "#A855F7", "#22D3EE", "#0F0904", "#F7EFE5", "Toonami & Action", "SPACE DANDY"),

    ("flcl", "FLCL", "The surreal coming-of-age story with guitars and robots.",
     "FLCL Agent", "Nothing amazing happens here... Type your message or /help.",
     "See you, Naota. Maybe.",
     "♬", ["hitting things with a bass guitar", "dealing with robots", "growing up", "eating bread", "going on adventures"],
     "#F472B6", "#F8FAFC", "#38BDF8", "#130A12", "#F9EBF3", "Toonami & Action", "FLCL"),

    ("big-o", "The Big O", "Roger Smith and the giant robot Big O in Paradigm City.",
     "Paradigm Agent", "Negotiation time. Type your message or /help.",
     "Cast in the name of God. Out.",
     "⬤", ["casting memories", "negotiating with the Big O", "solving mysteries", "driving the Big O", "facing the past"],
     "#6B7280", "#FACC15", "#FDE047", "#0B0C0E", "#ECEEF1", "Toonami & Action", "BIG O"),

    ("g-gundam", "Mobile Fighter G Gundam", "The Gundam Fight tournament decides Earth's fate.",
     "Fighter Agent", "Gundam Fight ready! Type your message or /help, fighter!",
     "The King of Hearts wins! Later!",
     "❃", ["fighting the Gundam Fight", "burning the Gundam", "training with the crew", "defending Earth", "going gold"],
     "#DC2626", "#22C55E", "#FDE047", "#0D0404", "#F6E9E9", "Toonami & Action", "G GUNDAM"),

    ("tenchi-muyo", "Tenchi Muyo", "An ordinary guy with extraordinary space friends.",
     "Tenchi Agent", "Welcome to the Masaki house! Type your message or /help.",
     "The universe is at peace. Later!",
     "❆", ["living with space pirates", "dealing with Juraian royalty", "going to school", "protecting the Earth", "having space adventures"],
     "#A855F7", "#4ADE80", "#FDE047", "#0D0714", "#F2ECF8", "Toonami & Action", "TENCHI MUYO"),

    ("sailor-moon", "Sailor Moon", "Usagi and the Sailor Guardians fight evil by moonlight.",
     "Guardian Agent", "Fighting evil by moonlight! Type your message or /help!",
     "Moon prism power! Goodbye!",
     "☾", ["transforming", "fighting evil by moonlight", "protecting love and justice", "activating Moon Prism Power", "fighting the Dark Kingdom"],
     "#F472B6", "#38BDF8", "#FDE047", "#120A14", "#F9EBF3", "Toonami & Action", "SAILOR MOON"),

    ("zoids", "Zoids", "Mecha beasts battling across the planet Zi.",
     "Zoid Pilot", "Zoid, launch! Type your message or /help, pilot!",
     "Battle won! Zoid out!",
     "◻", ["battling zoids", "riding the Liger", "pilot-ing", "fighting the Empire", "saving the planet"],
     "#2563EB", "#F97316", "#FDE047", "#060C16", "#E5ECF7", "Toonami & Action", "ZOIDS"),

    ("outlaw-star", "Outlaw Star", "Gene Starwind and the search for the Galactic Leyline.",
     "Outlaw Agent", "The Outlaw Star sets sail! Type your message or /help!",
     "The Galactic Leyline awaits. Later!",
     "✫", ["sailing the stars", "finding the Galactic Leyline", "hunting treasure", "fighting the pirates", "navigating the galaxy"],
     "#F59E0B", "#3B82F6", "#FDE047", "#0F0A03", "#F6F0E4", "Toonami & Action", "OUTLAW STAR"),

    ("rurouni-kenshin", "Rurouni Kenshin", "A wandering swordsman protecting the Meiji era.",
     "Kenshin Agent", "Oro? Type your message or /help, samurai.",
     "The wanderer continues his journey.",
     "✬", ["sword-ing", "protecting the Meiji era", "using the Hiten Mitsurugi style", "drifting", "defending the innocent"],
     "#DC2626", "#94A3B8", "#FDE047", "#0D0404", "#F6E9E9", "Toonami & Action", "KENSHIN"),

    ("deadman-wonderland", "Deadman Wonderland", "Ganta fights for survival in a deadly prison.",
     "Deadman Agent", "Welcome to Wonderland. Type your message or /help... if you survive.",
     "The carnival is over. Run.",
     "✮", ["surviving the prison", "using the Branch of Sin", "fighting the Deadmen", "escaping the carnival", "staying alive"],
     "#DC2626", "#6B7280", "#FDE047", "#0C0404", "#F6E8E8", "Toonami & Action", "DEADMAN"),

    ("trigun", "Trigun", "Vash the Stampede — the pacifist gunslinger with a $$60 billion bounty.",
     "Stampede Agent", "Love and peace! Type your message or /help!",
     "Love and peace! See you around!",
     "❊", ["dodging bullets", "love and peace", "outrunning the bounty", "protecting everyone", "drawing the Colt"],
     "#DC2626", "#E5E7EB", "#FACC15", "#0C0505", "#F5E9E9", "Toonami & Action", "TRIGUN"),

    ("bakugan", "Bakugan", "Battle brawlers with cards that spring into creatures.",
     "Brawler Agent", "Bakugan, brawl! Type your message or /help!",
     "Game over! Brawlers win!",
     "✦", ["brawling", "throwing Bakugan", "winning the game", "building a deck", "battling opponents"],
     "#3B82F6", "#EF4444", "#FDE047", "#070D16", "#E6EDF7", "Toonami & Action", "BAKUGAN"),

    ("beyblade", "Beyblade", "Spinning tops battle it out in the beystadium.",
     "Blader Agent", "Let it rip! Type your message or /help, blader!",
     "Spin finish! Great battle!",
     "◒", ["spinning", "letting it rip", "battling in the beystadium", "training the bit-beasts", "winning the tournament"],
     "#F59E0B", "#3B82F6", "#FDE047", "#0F0A03", "#F6F0E4", "Toonami & Action", "BEYBLADE"),

    ("beyblade-burst", "Beyblade Burst", "The Burst era — beys that burst apart at high speed.",
     "Blader Agent", "Let it rip... and burst! Type your message or /help!",
     "Burst finish! Amazing!",
     "◓", ["bursting", "spinning fast", "battling the Valkyrie", "training with the team", "breaking the beys"],
     "#F97316", "#22D3EE", "#FDE047", "#0E0803", "#F7EFE5", "Toonami & Action", "BEYBLADE BURST"),

    # ---------------- Adult Swim ----------------
    ("rick-and-morty", "Rick and Morty", "A genius mad scientist and his grandson across dimensions.",
     "Rick Agent", "Wubba lubba dub dub! Type your message or /help, Morty!",
     "I'm gonna go cry in the garage. Bye.",
     "✌", ["going on interdimensional adventures", "inventing gadgets", "saving the multiverse", "portal-ing", "being a genius (sort of)"],
     "#7DD3FC", "#4ADE80", "#FDE047", "#0A1418", "#EAF4F8", "Adult Swim", "RICK & MORTY"),

    ("aqua-teen-hunger-force", "Aqua Teen Hunger Force", "Master Shake, Frylock and Meatwad's bizarre suburban life.",
     "ATHF Agent", "Number one in the hood, G! Type your message or /help!",
     "Meatwad's asleep. Bye!",
     "☢", ["being number one in the hood", "fighting the Mooninites", "arguing", "eating food", "terrorizing the neighborhood"],
     "#4ADE80", "#38BDF8", "#FDE047", "#081209", "#E9F6EC", "Adult Swim", "AQUA TEEN"),

    ("robot-chicken", "Robot Chicken", "Stop-motion sketch comedy with pop-culture mayhem.",
     "Robot Chicken Agent", "Welcome to Robot Chicken! Type your message or /help.",
     "The chicken clucks goodbye!",
     "☓", ["sketch-ing", "poking fun", "smashing toys", "doing stop-motion", "cracking jokes"],
     "#94A3B8", "#EF4444", "#FDE047", "#0E1013", "#ECEEF1", "Adult Swim", "ROBOT CHICKEN"),

    ("space-ghost-coast-to-coast", "Space Ghost Coast to Coast", "A retired superhero hosts a talk show.",
     "Space Ghost Agent", "Welcome to Coast to Coast! Type your message or /help, guest.",
     "We're out of time. See you next show!",
     "✺", ["hosting the show", "interviewing guests", "fighting Zorak", "dealing with Moltar", "being a talk show host"],
     "#64748B", "#F472B6", "#FDE047", "#0B0D10", "#EBEDF0", "Adult Swim", "SPACE GHOST"),

    ("harvey-birdman", "Harvey Birdman, Attorney at Law", "A superhero lawyer defending cartoon characters.",
     "Birdman Agent", "You have the right to remain fabulous! Type your message or /help!",
     "Case dismissed! Birdman out!",
     "⚖", ["defending clients", "practicing law", "objecting", "fighting for justice", "working at the firm"],
     "#F59E0B", "#64748B", "#FDE047", "#0E0903", "#F6F0E3", "Adult Swim", "HARVEY BIRDMAN"),

    ("sealab-2021", "Sealab 2021", "A dysfunctional underwater research station.",
     "Sealab Agent", "Sealab 2021 online! Type your message or /help, crew.",
     "Sealab is sinking... again. Later!",
     "≈", ["working underwater", "dealing with the crew", "fixing the station", "diving", "surviving Sealab"],
     "#22D3EE", "#FB923C", "#FDE047", "#051214", "#E6F5F7", "Adult Swim", "SEALAB 2021"),

    ("venture-bros", "The Venture Bros.", "The Venture family — failed scientists and bodyguards.",
     "Venture Agent", "Go Team Venture! Type your message or /help!",
     "The compound is safe. Later!",
     "☂", ["going on adventures", "dealing with the Monarch", "inventing", "protecting the family", "failing upward"],
     "#64748B", "#FACC15", "#FDE047", "#0A0C0F", "#EBEDF0", "Adult Swim", "VENTURE BROS"),

    ("metalocalypse", "Metalocalypse", "The world's greatest death metal band, Dethklok.",
     "Dethklok Agent", "Brutal! Type your message or /help... or face the consequences!",
     "Dethklok out! Go into the water!",
     "⚝", ["being brutal", "rehearsing", "touring", "dealing with the Tribunal", "making music"],
     "#64748B", "#EF4444", "#FACC15", "#07080B", "#E8EBEF", "Adult Swim", "METALOCALYPSE"),

    ("squidbillies", "Squidbillies", "Squid-mountain-dwellers causing trouble in the backwoods.",
     "Cuyler Agent", "Howdy! Type your message or /help, kin.",
     "See ya around the creek!",
     "✗", ["squidding around", "causing trouble", "fighting the sheriff", "hunting", "being a Cuyler"],
     "#F97316", "#A16207", "#FDE047", "#0E0702", "#F7EFE4", "Adult Swim", "SQUIDBILLIES"),

    # ---------------- Acquired & International ----------------
    ("tom-and-jerry", "Tom and Jerry", "The eternal cat-and-mouse chase that needs no intro.",
     "Tom Agent", "Meow! Type your message or /help... before Jerry does.",
     "The chase continues. Later!",
     "✦", ["chasing Jerry", "setting traps", "getting outsmarted", "fighting for the house", "plotting revenge"],
     "#DC2626", "#6B7280", "#FDE047", "#0D0404", "#F6E9E9", "Acquired & International", "TOM & JERRY"),

    ("scooby-doo", "Scooby-Doo", "Mystery Inc. and the Mystery Machine solving spooky cases.",
     "Scooby Agent", "Ruh-roh! Type your message or /help, gang!",
     "And I would've gotten away with it too... bye!",
     "✧", ["solving mysteries", "unmasking villains", "running from ghosts", "eating Scooby Snacks", "driving the Mystery Machine"],
     "#4ADE80", "#D97706", "#FDE047", "#071407", "#E9F6EC", "Acquired & International", "SCOOBY DOO"),

    ("whats-new-scooby-doo", "What's New, Scooby-Doo?", "The 2000s Mystery Inc. — same gang, new mysteries.",
     "Scooby Agent", "Ruh-roh, Raggy! Type your message or /help!",
     "Mystery solved! Scooby Snacks for all!",
     "✳", ["solving mysteries", "unmasking the ghost", "chasing clues", "getting scared", "eating snacks"],
     "#22C55E", "#F59E0B", "#FDE047", "#061206", "#E8F6EA", "Acquired & International", "SCOOBY DOO"),

    ("scooby-doo-mystery-incorporated", "Scooby-Doo! Mystery Incorporated", "The darker serialized Mystery Inc. mystery.",
     "Mystery Inc Agent", "Crystal Cove has a mystery! Type your message or /help, gang.",
     "The plan is revealed. Scooby out!",
     "✹", ["uncovering the plan", "solving the curse", "exploring Crystal Cove", "fighting the demons", "unmasking the truth"],
     "#3B82F6", "#F59E0B", "#FDE047", "#060D16", "#E6EEF7", "Acquired & International", "MYSTERY INC"),

    ("johnny-test", "Johnny Test", "A boy and his genius sisters' experiments.",
     "Johnny Agent", "Johnny Test! Type your message or /help!",
     "Test complete! See ya!",
     "✸", ["testing things", "helping his sisters", "escaping monsters", "fighting Dukey", "causing trouble"],
     "#F97316", "#3B82F6", "#FDE047", "#0F0904", "#F7EFE5", "Acquired & International", "JOHNNY TEST"),

    ("garfield-show", "The Garfield Show", "The lasagna-loving cat and his friends.",
     "Garfield Agent", "I hate Mondays. Type your message or /help... and bring lasagna.",
     "Time for a nap. Goodbye!",
     "✿", ["eating lasagna", "napping", "annoying Jon", "outsmarting Odie", "hating Mondays"],
     "#F97316", "#FACC15", "#FDE047", "#0F0903", "#F7EFE4", "Acquired & International", "GARFIELD"),

    ("oggy-cockroaches", "Oggy and the Cockroaches", "A cat's quiet life ruined by three cockroaches.",
     "Oggy Agent", "Shhh... Type your message or /help before the roaches hear.",
     "Finally quiet... for now. Bye!",
     "✷", ["chasing cockroaches", "protecting the house", "getting pranked", "eating pizza", "staying calm"],
     "#38BDF8", "#A3E635", "#FDE047", "#070F14", "#E9F3F8", "Acquired & International", "OGGY"),

    ("zig-sharko", "Zig & Sharko", "A hyena's endless attempts to catch a mermaid.",
     "Zig Agent", "Splash! Type your message or /help!",
     "The mermaid got away... again! Bye!",
     "✾", ["chasing the mermaid", "scheming", "dealing with Sharko", "splashing around", "failing hilariously"],
     "#22D3EE", "#FB923C", "#FDE047", "#051214", "#E6F5F7", "Acquired & International", "ZIG & SHARKO"),

    ("grizzy-lemmings", "Grizzy and the Lemmings", "A bear vs. the lemmings in a national park cabin.",
     "Grizzy Agent", "Grrr! Type your message or /help... and watch the lemmings.",
     "The lemmings win... again. Bye!",
     "✹", ["fighting the lemmings", "protecting the cabin", "getting outsmarted", "watching TV", "raiding the fridge"],
     "#F59E0B", "#93C5FD", "#FDE047", "#0F0903", "#F6F0E3", "Acquired & International", "GRIZZY"),

    ("mr-bean-animated", "Mr. Bean: The Animated Series", "The beloved bumbling everyman, animated.",
     "Bean Agent", "Bean! Type your message or /help.",
     "Goodbye... Bean!",
     "✤", ["getting into trouble", "bumbling around", "solving problems (badly)", "driving the Mini", "causing chaos"],
     "#FACC15", "#64748B", "#FDE047", "#100D03", "#F9F5E4", "Acquired & International", "MR BEAN"),

    ("taffy", "Taffy", "A crafty cat and a dog in a mansion full of schemes.",
     "Taffy Agent", "Sneaky! Type your message or /help!",
     "Time for mischief. Bye!",
     "✺", ["scheming", "sneaking around", "outsmarting everyone", "finding snacks", "causing trouble"],
     "#F472B6", "#38BDF8", "#FDE047", "#120A12", "#F9EBF3", "Acquired & International", "TAFFY"),

    ("angelo-rules", "Angelo Rules", "A boy using elaborate plans to get what he wants.",
     "Angelo Agent", "Rule one: never give up! Type your message or /help!",
     "Mission accomplished! Later!",
     "✯", ["making plans", "outsmarting adults", "sneaking around", "following the rules", "getting what he wants"],
     "#F97316", "#22C55E", "#FDE047", "#0F0904", "#F7EFE5", "Acquired & International", "ANGELO RULES"),

    ("transformers-animated", "Transformers: Animated", "The Autobots as a repair crew in Detroit.",
     "Autobot Agent", "Autobots, roll out! Type your message or /help!",
     "Rolling out! Till all are one!",
     "✸", ["transforming", "rolling out", "fighting Decepticons", "repairing things", "protecting Detroit"],
     "#2563EB", "#EF4444", "#FACC15", "#060C16", "#E5ECF7", "Acquired & International", "TRANSFORMERS"),

    ("code-lyoko", "Code Lyoko", "Virtual warriors entering Lyoko to fight XANA.",
     "Lyoko Agent", "Lyoko online! Type your message or /help, warrior!",
     "Returning to reality. Lyoko out!",
     "◈", ["entering Lyoko", "fighting XANA", "scanner-ing", "virtually-world-ing", "saving the world"],
     "#3B82F6", "#A855F7", "#FDE047", "#070E18", "#E6EDF7", "Acquired & International", "CODE LYOKO"),

    ("mega-man-fully-charged", "Mega Man: Fully Charged", "The blue bomber reborn for a new generation.",
     "Mega Man Agent", "Mega Man, fully charged! Type your message or /help!",
     "Power down. See you next charge!",
     "✹", ["charging up", "blasting robots", "fighting Dr. Light's creations", "saving Silicon City", "power-ing up"],
     "#2563EB", "#F8FAFC", "#FDE047", "#060C16", "#E5ECF7", "Acquired & International", "MEGA MAN"),

    # ---------------- Cartoon Network India ----------------
    ("roll-no-21", "Roll No. 21", "Krishna, the mischievous kid who gets into magical trouble.",
     "Krishna Agent", "Roll no. 21, reporting! Type your message or /help!",
     "School's out! See you in class!",
     "✺", ["getting into trouble", "escaping the teacher", "doing mischief", "solving problems", "being the class clown"],
     "#F97316", "#22C55E", "#FDE047", "#100902", "#F7EFE4", "Cartoon Network India", "ROLL NO 21"),

    ("pakdam-pakdai", "Pakdam Pakdai", "Cat vs. mouse in a wacky, fast-paced chase.",
     "Pakdai Agent", "Here comes the chase! Type your message or /help!",
     "The mouse got away! Later!",
     "✽", ["chasing the mouse", "setting traps", "crashing through walls", "outsmarting the cat", "causing chaos"],
     "#FB923C", "#22D3EE", "#FDE047", "#100A04", "#F8F0E6", "Cartoon Network India", "PAKDAM PAKDAI"),

    ("gattu-battu", "Gattu Battu", "A boy and his faithful dog on everyday adventures.",
     "Gattu Agent", "Gattu and Battu ready! Type your message or /help!",
     "Battu says woof! Bye!",
     "✳", ["playing with Battu", "going on adventures", "helping neighbors", "being a good kid", "exploring the town"],
     "#F87171", "#60A5FA", "#FDE047", "#110606", "#F9EBEB", "Cartoon Network India", "GATTU BATTU"),

    ("rohan-anisha", "Rohan & Anisha", "A boy and his alien friend's city adventures.",
     "Rohan Agent", "Anisha's here! Type your message or /help!",
     "The city is safe. Bye!",
     "✱", ["going on adventures", "using alien powers", "helping the city", "avoiding the teacher", "being best friends"],
     "#38BDF8", "#F9A8D4", "#FDE047", "#070F16", "#E9F3F8", "Cartoon Network India", "ROHAN & ANISHA"),

    ("kumbh-karan", "Kumbh Karan", "The sleepy giant from the legends, now a lovable kid.",
     "Kumbh Agent", "Yawn... Type your message or /help... after my nap.",
     "Nap time... see you later... zzz.",
     "✹", ["napping", "waking up", "getting into trouble", "being hungry", "helping friends"],
     "#A855F7", "#FACC15", "#FDE047", "#0E0714", "#F3ECF8", "Cartoon Network India", "KUMBH KARAN"),

    ("chumbak", "Chumbak", "A magnet-powered kid attracting adventure.",
     "Chumbak Agent", "Magnetic power, activate! Type your message or /help!",
     "Magnet off! See you!",
     "✿", ["magnet-izing", "attracting trouble", "using magnetic powers", "helping the town", "sticking around"],
     "#22C55E", "#FB923C", "#FDE047", "#061206", "#E8F6EA", "Cartoon Network India", "CHUMBAK"),

    ("viramputin", "Viramputin", "A cartoonist's characters come to life in a wild town.",
     "Viramputin Agent", "Cartoons alive! Type your message or /help!",
     "Ink's dry. Bye!",
     "✵", ["drawing", "bringing characters to life", "escaping the villains", "making cartoons", "having wild adventures"],
     "#E879F9", "#22D3EE", "#FDE047", "#130820", "#F6EAF9", "Cartoon Network India", "VIRAMPUTIN"),

    ("supa-strikas", "Supa Strikas", "The world's best street football team.",
     "Strikas Agent", "Supa Strikas! Type your message or /help and play the game!",
     "Full-time! Great game!",
     "⚽", ["playing football", "scoring goals", "training with the team", "winning the match", "dribbling"],
     "#22C55E", "#FACC15", "#38BDF8", "#061206", "#E8F6EA", "Cartoon Network India", "SUPA STRIKAS"),

    ("lamput", "Lamput", "A blob of orange goo outsmarting two lab scientists.",
     "Lamput Agent", "Splat! Type your message or /help!",
     "Lamput escapes... again! Bye!",
     "❀", ["escaping the lab", "squishing", "outsmarting the scientists", "hiding", "being goo"],
     "#F472B6", "#38BDF8", "#FDE047", "#120A12", "#F9EBF3", "Cartoon Network India", "LAMPUT"),
]
