# -*- coding: utf-8 -*-
"""Per-show banner extras: hero icon key + themed skill list."""

# slug -> hero icon (see hero_icons.py)
ICON_MAP = {
    # Ben 10 Universe
    "ben-10": "omnitrix", "ben-10-alien-force": "omnitrix",
    "ben-10-ultimate-alien": "omnitrix", "ben-10-omniverse": "omnitrix",
    "ben-10-2016": "omnitrix", "generator-rex": "gear",
    # Cartoon Cartoons & Classics
    "powerpuff-girls": "heart", "powerpuff-girls-2016": "heart",
    "dexter-laboratory": "gear", "johnny-bravo": "star",
    "courage-the-cowardly-dog": "ghost", "ed-edd-n-eddy": "planet",
    "kids-next-door": "tree", "fosters-home": "house",
    "grim-adventures-of-billy-mandy": "skull", "samurai-jack": "eye",
    "cow-and-chicken": "star", "i-am-weasel": "crown",
    "2-stupid-dogs": "paw", "robot-jones": "gear",
    "mike-lu-og": "sun", "sheep-in-the-big-city": "ghost",
    "the-cramp-twins": "star", "camp-lazlo": "tree",
    "my-gym-partner-is-a-monkey": "paw", "squirrel-boy": "paw",
    "hi-hi-puffy-amiyumi": "flower", "juniper-lee": "moon",
    "class-of-3000": "star", "mucha-lucha": "sun",
    "the-problem-solverz": "bolt", "out-of-jimmys-head": "ghost",
    "chowder": "mug", "flapjack": "wave",
    "total-drama": "star", "total-dramarama": "heart",
    "6teen": "heart", "stoked": "wave",
    "robotboy": "gear", "megas-xlr": "gear",
    "xiaolin-showdown": "ninja-star", "secret-saturdays": "eye",
    "sym-bionic-titan": "shield", "hero-108": "ninja-star",
    "chop-socky-chooks": "ninja-star", "skatoony": "star",
    "hot-wheels-battle-force-5": "rocket", "monster-beach": "ghost",
    "ducks-dodgers": "rocket", "loonatics-unleashed": "bolt",
    "baby-looney-tunes": "heart", "krypto-superdog": "paw",
    # Modern Cartoon Network
    "adventure-time": "star", "regular-show": "star",
    "the-amazing-world-of-gumball": "planet", "steven-universe": "star",
    "we-bare-bears": "paw", "we-baby-bears": "paw",
    "uncle-grandpa": "sun", "clarence": "sun",
    "craig-of-the-creek": "tree", "ok-ko": "bolt",
    "infinity-train": "rocket", "apple-onion": "sun",
    "victor-valentino": "moon", "mao-mao": "shield",
    "summer-camp-island": "tree", "elliott-from-earth": "planet",
    "mighty-magiswords": "ninja-star", "annoying-orange": "planet",
    "teen-titans-go": "star", "jade-armor": "shield",
    "unikitty": "heart", "mixels": "gear",
    "thundercats-roar": "paw", "dreamworks-dragons": "flame",
    # DC Super Heroes
    "teen-titans": "shield", "justice-league": "shield",
    "justice-league-unlimited": "shield", "batman-tas": "bat",
    "batman-beyond": "bat", "static-shock": "bolt",
    "zeta-project": "gear", "young-justice": "bolt",
    "green-lantern-tas": "planet", "beware-the-batman": "bat",
    "justice-league-action": "star", "dc-super-hero-girls": "star",
    "batman-brave-bold": "bat",
    # Star Wars & LEGO
    "star-wars-clone-wars": "rocket", "ninjago": "ninja-star",
    "lego-monkie-kid": "ninja-star", "lego-city-adventures": "house",
    "thundercats-2011": "paw",
    # Toonami & Action
    "toonami": "rocket", "dragon-ball-z": "dragon-ball",
    "dragon-ball-gt": "dragon-ball", "dragon-ball-super": "dragon-ball",
    "naruto": "spiral", "naruto-shippuden": "spiral",
    "one-piece": "skull", "bleach": "skull",
    "cowboy-bebop": "rocket", "samurai-champloo": "sun",
    "eureka-seven": "wave", "inuyasha": "moon",
    "fullmetal-alchemist": "gear", "yu-yu-hakusho": "bolt",
    "hunter-x-hunter": "star", "attack-on-titan": "shield",
    "my-hero-academia": "star", "jojo-bizarre-adventure": "star",
    "mob-psycho-100": "eye", "demon-slayer": "flame",
    "sword-art-online": "ninja-star", "one-punch-man": "bolt",
    "dr-stone": "gear", "fire-force": "flame",
    "gundam-wing": "gear", "gundam-00": "gear",
    "space-dandy": "rocket", "flcl": "star",
    "big-o": "gear", "g-gundam": "flame",
    "tenchi-muyo": "planet", "sailor-moon": "moon",
    "zoids": "paw", "outlaw-star": "rocket",
    "rurouni-kenshin": "moon", "deadman-wonderland": "skull",
    "trigun": "sun", "bakugan": "planet",
    "beyblade": "planet", "beyblade-burst": "planet",
    # Adult Swim
    "rick-and-morty": "portal", "aqua-teen-hunger-force": "sun",
    "robot-chicken": "star", "space-ghost-coast-to-coast": "rocket",
    "harvey-birdman": "star", "sealab-2021": "wave",
    "venture-bros": "shield", "metalocalypse": "skull",
    "squidbillies": "moon",
    # Acquired & International
    "tom-and-jerry": "paw", "scooby-doo": "ghost",
    "whats-new-scooby-doo": "ghost", "scooby-doo-mystery-incorporated": "ghost",
    "johnny-test": "star", "garfield-show": "sun",
    "oggy-cockroaches": "paw", "zig-sharko": "wave",
    "grizzy-lemmings": "paw", "mr-bean-animated": "sun",
    "taffy": "paw", "angelo-rules": "bolt",
    "transformers-animated": "gear", "code-lyoko": "bolt",
    "mega-man-fully-charged": "gear",
    # Cartoon Network India
    "roll-no-21": "sun", "pakdam-pakdai": "paw",
    "gattu-battu": "paw", "rohan-anisha": "planet",
    "kumbh-karan": "moon", "chumbak": "bolt",
    "viramputin": "star", "supa-strikas": "sun",
    "lamput": "ghost",
}

# slug -> main-character portrait (see character_art.py). Shows without an
# entry keep their themed icon art.
CHARACTER_MAP = {
    "ben-10": "ben", "ben-10-2016": "ben", "ben-10-omniverse": "ben",
    "powerpuff-girls": "ppg", "powerpuff-girls-2016": "ppg",
    "dexter-laboratory": "dexter", "johnny-bravo": "bravo",
    "courage-the-cowardly-dog": "courage", "kids-next-door": "knd",
    "fosters-home": "bloo", "samurai-jack": "jack",
    "adventure-time": "finn", "regular-show": "mordecai",
    "the-amazing-world-of-gumball": "gumball", "steven-universe": "steven",
    "we-bare-bears": "bears", "we-baby-bears": "bears",
    "batman-tas": "batman", "batman-beyond": "beyond",
    "beware-the-batman": "batman", "batman-brave-bold": "batman",
    "star-wars-clone-wars": "clone", "ninjago": "ninja",
    "toonami": "tom",
    "dragon-ball-z": "goku", "dragon-ball-gt": "goku", "dragon-ball-super": "goku",
    "naruto": "naruto", "naruto-shippuden": "naruto",
    "one-piece": "luffy", "my-hero-academia": "deku",
    "one-punch-man": "saitama",
    "gundam-wing": "gundam", "gundam-00": "gundam", "g-gundam": "gundam",
    "sailor-moon": "usagi", "rick-and-morty": "rick",
    "aqua-teen-hunger-force": "shake",
    "tom-and-jerry": "tomcat", "scooby-doo": "scooby",
    "whats-new-scooby-doo": "scooby", "scooby-doo-mystery-incorporated": "scooby",
    "garfield-show": "garfield", "transformers-animated": "optimus",
    "mega-man-fully-charged": "megaman",
}

# slug -> short themed skills shown in the banner
SKILLS_MAP = {
    # Ben 10 Universe
    "ben-10": ["Alien Transformation", "Omnitrix Mastery", "Hero Time"],
    "ben-10-alien-force": ["Team Leadership", "Plumber Training", "Alien Summoning"],
    "ben-10-ultimate-alien": ["Ultimate Evolution", "Galaxy Mapping", "Power Scanning"],
    "ben-10-omniverse": ["Timeline Repair", "Alien Fusion", "Omnitrix Reboot"],
    "ben-10-2016": ["Road Trip Heroics", "Quick-Dial Aliens", "Summer Missions"],
    "generator-rex": ["Nanite Building", "EVO Hunting", "Machine Summoning"],
    # Cartoon Cartoons & Classics
    "powerpuff-girls": ["Super Speed", "Crime Fighting", "Bedtime Evasion"],
    "powerpuff-girls-2016": ["Neon Power", "Villain Punching", "Teamwork"],
    "dexter-laboratory": ["Secret Inventions", "Lab Engineering", "Dee Dee Dodging"],
    "johnny-bravo": ["Hair Combing", "Charm Offense", "Smooth Moves"],
    "courage-the-cowardly-dog": ["Nowhere Survival", "Monster Defusing", "Loyalty"],
    "ed-edd-n-eddy": ["Scam Crafting", "Jawbreaker Hunting", "Quarter Collecting"],
    "kids-next-door": ["Treehouse Ops", "Sector Defense", "Adult Resistance"],
    "fosters-home": ["Friend Imagining", "Adoption Matching", "House Shuffling"],
    "grim-adventures-of-billy-mandy": ["Deal Cursing", "Scythe Handling", "Endsville Travel"],
    "samurai-jack": ["Katana Mastery", "Aku Hunting", "Timeline Defense"],
    "cow-and-chicken": ["Moo Communication", "Red Guy Evasion", "Sibling Chaos"],
    "i-am-weasel": ["Brilliance", "Posing", "Baboon Outsmarting"],
    "2-stupid-dogs": ["Hole Digging", "Tail Chasing", "Happiness"],
    "robot-jones": ["Emotion Processing", "Reboot Cycle", "Middle School Survival"],
    "mike-lu-og": ["Island Crafting", "Gadget Building", "Culture Exchange"],
    "sheep-in-the-big-city": ["Military Evasion", "Wool Management", "City Hiding"],
    "the-cramp-twins": ["Twin Telepathy", "Prank Engineering", "Neighbor Annoying"],
    "camp-lazlo": ["Bean Scouting", "Jellybean Rescue", "Campfire Skills"],
    "my-gym-partner-is-a-monkey": ["Monkey Business", "Gym Class", "Animal Friendship"],
    "squirrel-boy": ["Nut Hoarding", "Mischief Planning", "Acorn Accuracy"],
    "hi-hi-puffy-amiyumi": ["Rock Performance", "Japan Touring", "Chart Topping"],
    "juniper-lee": ["Monster Brawling", "Magic Secrecy", "Guardian Duty"],
    "class-of-3000": ["Music Teaching", "Beat Making", "Harmony Building"],
    "mucha-lucha": ["Masked Wrestling", "Rope Flying", "Championship Moves"],
    "the-problem-solverz": ["Problem Solving", "Neon Engineering", "Deal Making"],
    "out-of-jimmys-head": ["Imagination Control", "Blob Escape", "Cartoon Mixing"],
    "chowder": ["Recipe Learning", "Food Tasting", "Kitchen Chaos"],
    "flapjack": ["Pirate Sailing", "Candy Navigation", "Talking Whale"],
    "total-drama": ["Challenge Survival", "Alliance Building", "Elimination Dodging"],
    "total-dramarama": ["Naptime Mastery", "Snack Strategy", "Toddler Chaos"],
    "6teen": ["Mall Navigation", "Retail Skills", "Hangout Coordination"],
    "stoked": ["Wave Riding", "Resort Work", "Beach Survival"],
    "robotboy": ["Super Activation", "Target Destruction", "Protection Mode"],
    "megas-xlr": ["Mech Piloting", "Klorg Defeating", "Car Wrenching"],
    "xiaolin-showdown": ["Shen Gong Wu Hunting", "Kung Fu Training", "Showdown Strategy"],
    "secret-saturdays": ["Cryptid Tracking", "Legend Research", "Family Ops"],
    "sym-bionic-titan": ["Mech Piloting", "Alien Disguise", "Earth Defense"],
    "hero-108": ["Animal Army", "First Strike", "Hidden Valley Defense"],
    "chop-socky-chooks": ["Kung Fu Clucking", "Shop Defense", "Wing Combat"],
    "skatoony": ["Skate Tricks", "Trivia Mastery", "Wipeout Recovery"],
    "hot-wheels-battle-force-5": ["Turbo Racing", "Sark Battling", "Vehicle Transform"],
    "monster-beach": ["Graveyard Surfing", "Tourist Scaring", "Undead Socializing"],
    "ducks-dodgers": ["Space Heroics", "Marvin Evasion", "Quack Tactics"],
    "loonatics-unleashed": ["Acme Arsenal", "Metropolis Saving", "Super Agility"],
    "baby-looney-tunes": ["Napping", "Toy Diplomacy", "Daycare Survival"],
    "krypto-superdog": ["Super Bark", "Villain Fetching", "Family Protection"],
    # Modern Cartoon Network
    "adventure-time": ["Dungeon Exploring", "Ooo Navigation", "Math Counting"],
    "regular-show": ["Slack Management", "Video Game Skills", "Death Escape"],
    "the-amazing-world-of-gumball": ["Elmore Survival", "Family Chaos", "Detention Evasion"],
    "steven-universe": ["Gem Fusion", "Bubble Shields", "Beach City Protection"],
    "we-bare-bears": ["Brotherhood", "Food Ordering", "Hibernation Prep"],
    "we-baby-bears": ["Portal Hopping", "Snack Finding", "Adventure Cuteness"],
    "uncle-grandpa": ["Good Morning", "RV Driving", "Nephew Helping"],
    "clarence": ["Sunshine", "Friend Making", "Aberdale Exploring"],
    "craig-of-the-creek": ["Creek Mapping", "Kid Diplomacy", "Treasure Hunting"],
    "ok-ko": ["Hero Training", "Robot Punching", "Level Up"],
    "infinity-train": ["Number Solving", "Car Hopping", "Passenger Counseling"],
    "apple-onion": ["Pancake Making", "City Jamming", "Best Friendship"],
    "victor-valentino": ["Folklore Navigation", "Chupacabra Chasing", "Monte Macabre Survival"],
    "mao-mao": ["Pure Heart Defense", "Snugglemagne Riding", "Sky Pirate Hunting"],
    "summer-camp-island": ["Signal Sending", "Magical Friendship", "S'more Crafting"],
    "elliott-from-earth": ["Earth Exploration", "Human Learning", "Dinosaur Keeping"],
    "mighty-magiswords": ["Magisword Wielding", "Dungeon Crawling", "Riddle Solving"],
    "annoying-orange": ["Annoying", "Pun Delivery", "Knife Dodging"],
    "teen-titans-go": ["Pizza Acquisition", "Silly Heroics", "Song Breaks"],
    "jade-armor": ["Jade Power", "Dragon Training", "City Protection"],
    "unikitty": ["Sparkle Control", "Rage Management", "Party Hosting"],
    "mixels": ["Mix Building", "Nixel Fighting", "Combo Creation"],
    "thundercats-roar": ["Sword Summoning", "Silly Combat", "Mumm-Ra Baffling"],
    "dreamworks-dragons": ["Dragon Riding", "Berk Defense", "Toothless Training"],
    # DC Super Heroes
    "teen-titans": ["Team Assemble", "Slade Hunting", "Jump City Protection"],
    "justice-league": ["Watchtower Patrol", "Darkseid Fighting", "World Defense"],
    "justice-league-unlimited": ["Hero Coordination", "Cadmus Countering", "Global Protection"],
    "batman-tas": ["Shadow Stealth", "Gotham Patrol", "Rogue Hunting"],
    "batman-beyond": ["Suit Hacking", "Neo-Gotham Gliding", "Inque Fighting"],
    "static-shock": ["Electrokinesis", "Dakota Protection", "Bang Baby Rescue"],
    "zeta-project": ["Undercover Ops", "Evasion", "Hologram Disguise"],
    "young-justice": ["Covert Missions", "Mountain Training", "The Light Fighting"],
    "green-lantern-tas": ["Ring Constructs", "Sector 2814 Patrol", "Lantern Corps"],
    "beware-the-batman": ["Interrogation", "Cabal Dismantling", "Katana Teamwork"],
    "justice-league-action": ["Quick Response", "Villain Capture", "Team Up"],
    "dc-super-hero-girls": ["Super School", "Villain Fighting", "Fashion Patrol"],
    "batman-brave-bold": ["Hero Teaming", "Wisecracking", "Signal Answering"],
    # Star Wars & LEGO
    "star-wars-clone-wars": ["Clone Deployment", "Lightsaber Training", "Republic Defense"],
    "ninjago": ["Spinjitzu", "Elemental Powers", "Serpentine Fighting"],
    "lego-monkie-kid": ["Staff Wielding", "Cloud Riding", "Demon Hunting"],
    "lego-city-adventures": ["City Building", "Crime Catching", "Fire Rescue"],
    "thundercats-2011": ["Sword of Omens", "Thundera Defense", "Mumm-Ra Fighting"],
    # Toonami & Action
    "toonami": ["Midnight Lineup", "Power Up", "System Boot"],
    "dragon-ball-z": ["Kamehameha", "Super Saiyan", "Zenkai Boost"],
    "dragon-ball-gt": ["Golden Oozaru", "Black Star Balls", "Galaxy Travel"],
    "dragon-ball-super": ["Ultra Instinct", "God Ki", "Tournament Fighting"],
    "naruto": ["Shadow Clone", "Rasengan", "Ramen Appreciation"],
    "naruto-shippuden": ["Sage Mode", "Nine Tails Control", "Hokage Training"],
    "one-piece": ["Gum-Gum Power", "Grand Line Sailing", "Pirate King Dream"],
    "bleach": ["Bankai Release", "Hollow Hunting", "Soul Society"],
    "cowboy-bebop": ["Bounty Hunting", "Swordfish Piloting", "Jazz Timing"],
    "samurai-champloo": ["Blade Flips", "Edo Navigation", "Sunflower Search"],
    "eureka-seven": ["Trapar Riding", "Nirvash Piloting", "Skateboarding"],
    "inuyasha": ["Sit Training", "Shard Hunting", "Naraku Fighting"],
    "fullmetal-alchemist": ["Equivalent Exchange", "Transmutation", "Philosopher's Stone Search"],
    "yu-yu-hakusho": ["Spirit Gun", "Dark Tournament", "Demon Hunting"],
    "hunter-x-hunter": ["Nen Mastery", "Hunter Exam", "Ging Search"],
    "attack-on-titan": ["ODM Maneuvering", "Titan Slaying", "Wall Defense"],
    "my-hero-academia": ["One For All", "Plus Ultra", "Quirk Training"],
    "jojo-bizarre-adventure": ["Stand Power", "Posing", "Za Warudo"],
    "mob-psycho-100": ["Psychic Energy", "Emotional Control", "100% Mode"],
    "demon-slayer": ["Breathing Techniques", "Nezuko Protection", "Hashira Training"],
    "sword-art-online": ["Floor Clearing", "Dual Blades", "Aincrad Survival"],
    "one-punch-man": ["One Punch", "Hero Association", "Caped Baldy"],
    "dr-stone": ["Science Revival", "Invention", "Stone World Building"],
    "fire-force": ["Flame Control", "Infernal Fighting", "Company 8"],
    "gundam-wing": ["Gundam Piloting", "Colony Defense", "Zero System"],
    "gundam-00": ["GN Drive", "Intervention", "Celestial Being"],
    "space-dandy": ["Alien Hunting", "Galaxy Exploring", "Dandy Style"],
    "flcl": ["Bass Guitar Combat", "Robot Battling", "Coming of Age"],
    "big-o": ["Memory Casting", "Paradigm City", "Negotiation"],
    "g-gundam": ["Gundam Fight", "Burning Finger", "King of Hearts"],
    "tenchi-muyo": ["Space Adjacent", "Juraian Diplomacy", "Maser House"],
    "sailor-moon": ["Moon Prism Power", "Guardian Team", "Love and Justice"],
    "zoids": ["Zoid Piloting", "Liger Riding", "Empire Battling"],
    "outlaw-star": ["Galactic Leyline", "Ship Navigation", "Pirate Fighting"],
    "rurouni-kenshin": ["Hiten Mitsurugi", "Reverse Blade", "Wandering Protection"],
    "deadman-wonderland": ["Branch of Sin", "Prison Survival", "Carnival Escape"],
    "trigun": ["Bullet Dodging", "Love and Peace", "Colt Drawing"],
    "bakugan": ["Bakugan Brawl", "Card Strategy", "Battle Arena"],
    "beyblade": ["Spin Launch", "Bit-Beast Control", "Tournament Victory"],
    "beyblade-burst": ["Burst Finish", "Valkyrie Power", "Speed Spin"],
    # Adult Swim
    "rick-and-morty": ["Portal Travel", "Gadget Invention", "Multiverse Survival"],
    "aqua-teen-hunger-force": ["Neighborhood Dominance", "Mooninite Fighting", "Fast Food"],
    "robot-chicken": ["Stop-Motion", "Pop Culture Satire", "Toy Destruction"],
    "space-ghost-coast-to-coast": ["Talk Show Hosting", "Zorak Wrestling", "Coast to Coast"],
    "harvey-birdman": ["Legal Defense", "Objection", "Sebben & Sebben"],
    "sealab-2021": ["Underwater Ops", "Crew Management", "Station Repair"],
    "venture-bros": ["Adventure Science", "Monarch Evasion", "Team Venture"],
    "metalocalypse": ["Brutal Music", "Dethklok Touring", "Tribunal Evasion"],
    "squidbillies": ["Backwoods Survival", "Cuyler Chaos", "Sheriff Evasion"],
    # Acquired & International
    "tom-and-jerry": ["Trap Setting", "Chase Mastery", "House Defense"],
    "scooby-doo": ["Mystery Solving", "Snack Acquisition", "Villain Unmasking"],
    "whats-new-scooby-doo": ["Clue Chasing", "Ghost Unmasking", "Mystery Machine"],
    "scooby-doo-mystery-incorporated": ["Curse Solving", "Crystal Cove", "Plan Uncovering"],
    "johnny-test": ["Sister Tech", "Dukey Defense", "Trouble Finding"],
    "garfield-show": ["Lasagna Cooking", "Monday Hating", "Cat Napping"],
    "oggy-cockroaches": ["Roach Repelling", "Quiet Living", "Pizza Protection"],
    "zig-sharko": ["Mermaid Chasing", "Hyena Scheming", "Splash Survival"],
    "grizzy-lemmings": ["Cabin Defense", "TV Watching", "Lemming Outsmarting"],
    "mr-bean-animated": ["Bumbling", "Mini Driving", "Trouble Attracting"],
    "taffy": ["Sneaking", "Scheme Crafting", "Snack Finding"],
    "angelo-rules": ["Plan Execution", "Adult Outsmarting", "Rule Breaking"],
    "transformers-animated": ["Transformation", "Decepticon Fighting", "Repair Duty"],
    "code-lyoko": ["Lyoko Entry", "XANA Fighting", "Scanner Travel"],
    "mega-man-fully-charged": ["Charge Shot", "Robot Battle", "Silicon City"],
    # Cartoon Network India
    "roll-no-21": ["Mischief Mastery", "Teacher Evasion", "Magical Trouble"],
    "pakdam-pakdai": ["Chase Speed", "Trap Setting", "Wall Crashing"],
    "gattu-battu": ["Dog Friendship", "Neighbor Helping", "Adventure Time"],
    "rohan-anisha": ["Alien Powers", "City Exploring", "Best Friend Team"],
    "kumbh-karan": ["Power Napping", "Giant Strength", "Snack Appetite"],
    "chumbak": ["Magnet Power", "Trouble Attracting", "Town Helping"],
    "viramputin": ["Cartoon Drawing", "Character Creation", "Villain Escaping"],
    "supa-strikas": ["Dribbling", "Goal Scoring", "Team Tactics"],
    "lamput": ["Squish Escape", "Lab Evasion", "Goo Transformation"],
}
